### ISSUE TITLE
limel-button doesn't change size when changing the size of the `<limel-button>` element

### ISSUE THREAD

**Issue by adrianschmidt** [Lundalogik/lime-elements#1004]
## Current behavior

When setting the height and width of `<limel-button>`, only the container element changes size:

![image](https://user-images.githubusercontent.com/154725/97553236-7f55f400-19d5-11eb-976d-eea3e088b9b5.png)

## Expected behavior

The button should follow the size of the container element:

![image](https://user-images.githubusercontent.com/154725/97553455-bb895480-19d5-11eb-97f0-b0831deeefd8.png)

## Environment

- **lime-elements** version: 29.3.1 but probably affects all versions
- Framework used: reproducible in docs
- Logs:

**Comment by adrianschmidt** [comment]
We might want to add some design guidelines regarding when it's a good idea to change the size of the button, and when it should be avoided…

I can see legitimate use cases at least for controlling the width of buttons, as you might want to have buttons of the same width regardless of the length of their labels.

**Comment by adrianschmidt** [comment]
This should be pretty trivial to fix. The `<button>` element needs to have `height: 100%; min-height: 2.5rem; width: 100%;` and that should pretty much be it. The examples in the docs will need to be updated slightly though, as the `<limel-button-element>` has been given `display: block`, and that needs to be removed, and the button placed in a div instead (haven't tried it, but that ought to work).

**Comment by anderssonjohan** [comment]
Yes, this would be much appreciated in this kind of UI:

<img width="1009" alt="Screenshot 2020-11-02 at 17 07 34" src="https://user-images.githubusercontent.com/435885/97890673-1a303480-1d2e-11eb-88e1-a53104882ec6.png">

And with responsive grid layouts where you want up to two buttons per row in mobile views and need the button to fill the given grid area:

<img width="370" alt="Screenshot 2020-11-02 at 17 10 34" src="https://user-images.githubusercontent.com/435885/97891014-8d39ab00-1d2e-11eb-96b2-d8a35b427cbc.png">
<img width="362" alt="Screenshot 2020-11-02 at 17 13 26" src="https://user-images.githubusercontent.com/435885/97891375-ff11f480-1d2e-11eb-8255-5eb3c1ec7ab6.png">
<img width="373" alt="Screenshot 2020-11-02 at 17 15 09" src="https://user-images.githubusercontent.com/435885/97891383-00dbb800-1d2f-11eb-978e-2f79f7c739e5.png">

**Comment by eketorp** [comment]
I think Johan's examples look good. On small devices it makes sense to fill the screen x-wise. Should there be a max width so that the button doesn't expand too much? Would probably look weird on tablets and bigger devices.

**Comment by adrianschmidt** [comment]
> I think Johan's examples look good. On small devices it makes sense to fill the screen x-wise. Should there be a max width so that the button doesn't expand too much? Would probably look weird on tablets and bigger devices.

I think that should be up to the consumer (when we say "consumer" in lime-elements, we mean _the code that's using a lime-elements component_, like a Lime CRM add-on that uses limel-button for example). We can't set a global max-width for any consumer regardless of where they might be using lime-elements.
