### ISSUE TITLE
Reasonable z-index for limel-dialog

### ISSUE THREAD

**Issue by anderssonjohan** [Lundalogik/lime-elements#1020]
Question: Should we increase the z-index of limel-dialog?

When using limel-dialog, it's easy to have it displayed underneath something else because of the quite low z-index value used. The dialog uses the value 7, the same as the main navigation of Lime CRM Webclient.
Other frameworks, like Bootstrap, uses 1040 for modals+backdrops. Also, if you use tooltip components etc you need to have even higher z-index to have them render properly to not be hidden by the modal.
The next question is if a modal should render over something like the main navigation of Lime CRM and the dialog backdrop shouldn't?

My humble thoughts about z-indexes among these components, ranked in highest-first order:

* (tooltips)
* menu
* dialog (and FABs, off-canvas menus, but neither should render at the same time)
* fixed positioned navigation (like Kompendium)
* other content

Some simple examples of this issue can be seen with Kompendium running the fullscreen dialog example, where the main navigation uses a higher z-index compared to the limel-dialog's and is rendered on top of the fullscreen dialog.

<img width="742" alt="Screenshot 2020-11-03 at 22 05 02" src="https://user-images.githubusercontent.com/435885/98040575-c5b9b180-1e20-11eb-88fe-0132f0d68c0a.png">
<img width="303" alt="Screenshot 2020-11-03 at 22 04 38" src="https://user-images.githubusercontent.com/435885/98040579-c7837500-1e20-11eb-9a5b-625f3d9eca5c.png">

Some more reading/background on the z-index (wars, if you will):
https://coder-coder.com/z-index-isnt-working/
 

## Environment

- **lime-elements** version: 29.4.3
- Framework used: 
- Logs:

**Comment by adrianschmidt** [comment]
Yeah the 🤬🤬🤬🤬🤬🤬🤬🤬🤬🤬🤬🤬🤬🤬🤬🤬 z-index is always a 🤬 problem. We've had a low z-index because it was needed for something, I don't remember exactly why, if it was lime-webclient that required it or conflict with docz that we used before kompendium or something.

This is yet another of those over-arching design questions we need to do some work on some time.

I'm perfectly happy not to have a longwinded discussion about this during our dev-cycle, but if anyone else fancies it, then go ahead.

**Comment by adrianschmidt** [comment]
I just added #1107, which will make z-indexes overridable by the consumer. We may still want to tweak our default values after that, but it's a good starting point for very little effort.

**Comment by adrianschmidt** [comment]
PR #1137 adds a consumer-overridable css property `--dialog-z-index` to `limel-dialog`. To adjust the z-index of dropdowns such as those in `limel-menu` and `limel-select`, add styling to the global scope, targeting the `.limel-portal--container` selector. See the change to `src/index.html` in the PR for an example.

**Comment by adrianschmidt** [comment]
@anderssonjohan #1137 is up for review, and I'd welcome your input 🙂

**Comment by anderssonjohan** [comment]
@adrianschmidt LGTM - I have nothing to comment on, nice work! 👏
