### ISSUE TITLE
limel-table: rows are partially and sometimes completely cut from the bottom of the table

### ISSUE THREAD

**Issue by adrianschmidt** [Lundalogik/lime-elements#1044]
## Current behavior

First example in docs:

![image](https://user-images.githubusercontent.com/154725/99783070-3992d400-2b1a-11eb-9bbb-a308e0695aae.png)

Despite the last row being partially cut, the table cannot be scrolled vertically.

What's worse, in the second example, the whole last row is obscured, which is very easily missed:

![table obscuring last row](https://user-images.githubusercontent.com/154725/99784185-b83c4100-2b1b-11eb-8193-14a876f69274.gif)

## Expected behavior

I would expect that if any row is cut at all, the table would be possible to scroll vertically. At the very least, I would expect to be able to scroll if the cut is large enough to start obscuring the text, like in the screen shot.

## Environment

- **lime-elements** version: 29.7.0
- Framework used: Reproducible in docs
- Logs:

**Comment by adrianschmidt** [comment]
I've checked the related-table in the redesign in my local lime-webclient, but it doesn't appear there. I'm not sure why. Maybe we have some styling in the docs that makes this appear?

If this bug can actually appear in lime-webclient as it is now, then I think this is a fairly serious bug, as it may obscure data in a way that can be very hard for the user to notice.

If, on the other hand, it only happens when some particular styling is applied, which we happen to apply in the docs, then I don't think this is very urgent, but it should still be fixed, or at the very least we should find out when it happens and add a caution against it in the docs (if we can't fix it, or deem it not worth fixing).

@magnusfagerlund Ping!

**Comment by eketorp** [comment]
If this hasn't been reproduced in the client I would agree that it's not urgent.
I'm going to try to not leave non-urgent tickets "hanging" in the backlog because then it'll grow endlessly. I'm sure it will come back to us if it's worth fixing.
