### ISSUE TITLE
limel-table: local pagination is broken (at least in the docs)

### ISSUE THREAD

**Issue by adrianschmidt** [Lundalogik/lime-elements#1045]
## Current behavior

In the example for "Local sorting and pagination", only the first 10 rows are shown, as expected, but there are no controls for navigating between "pages" visible:

![image](https://user-images.githubusercontent.com/154725/99786005-3e598700-2b1e-11eb-9d73-c562ed6c1cee.png)

## Expected behavior

The controls for navigating between "pages" should be visible and functional regardless of whether local or remote pagination is used.

## Environment

- **lime-elements** version: 29.7.1
- Framework used: Reproducible in docs
- Logs:

**Comment by adrianschmidt** [comment]
We don't use the local pagination option in the stuff currently built into the Lime CRM Web Client (lime-crm-components to be precise), but add-ons may use it, and in general, if we provide the option, it should be functional 🙂

**Comment by eketorp** [comment]
I agree. But I would consider this not urgent. I don't want to use our efforts to solve this if no one uses it.
