### ISSUE TITLE
limel-select alternatives displayed in the top of the dialog

### ISSUE THREAD

**Issue by sofiehelgesson** [Lundalogik/lime-elements#1052]
## Current behavior
As the last field in my dialog I have a limel-select and if I have choosen the last alternative and presses the field again the alternatives list is shown in the top of the dialog. If the first alternative (Yes) is choosen the list displays correct.

![image](https://user-images.githubusercontent.com/24894627/100718379-8f3d6b00-33bb-11eb-90a9-4b301170b449.png)
![image](https://user-images.githubusercontent.com/24894627/100718634-db88ab00-33bb-11eb-9890-7d4bda62c972.png)

## Environment
- **lime-elements** version: 28.4.3

**Comment by adrianschmidt** [comment]
This was fixed in #1110, which is included in Lime Elements v30.7.1.

I'll close this issue. If the bug can be reproduced when v30.7.1 or later is used, please reopen it.
