### ISSUE TITLE
limel-picker: Clicking the button to remove all chips when the dropdown is open breaks the picker

### ISSUE THREAD

**Issue by FredrikWallstrom** [Lundalogik/lime-elements#1062]
## Current behavior

Clicking the x icon to the right (is it even needed at all?) makes it impossible to get the drop down to close again by clicking outside the drop down.

![97188322-acbb5b80-17a3-11eb-9f9e-c8604dd008bb](https://user-images.githubusercontent.com/21986391/101456222-0a5ece00-3934-11eb-919b-cd370719bae1.gif)

1. In a limel-picker that is configured with `multiple=true`, select one or more items
2. Open the dropdown again (you may have to click outside first, then on the picker again, this is a separate bug: #1064)
3. Hover the remove-button on the right edge of the picker, note that it does indicate that it can be clicked:
   ![image](https://user-images.githubusercontent.com/154725/101472512-fd000e80-3948-11eb-8e0a-1096fb2b4ffd.png)
   Important! Use the remove-button for removing all chips at once, _not_ the one on the chip itself (see separate bug concerning that one: #1063)
4. Click on the button

- The chips remain in the picker
- The picker is blurred, but the dropdown remains open
- Clicking outside the picker does not close the dropdown
- Clicking on the input does not focus the picker again
- Clicking on the remove button of a chip does nothing
- Clicking on the remove-all button does nothing
- At this point, there is only one way to close the picker: you have to select an item in the dropdown, once you do, the picker works as normal again

## Expected behavior

- All chips should be removed
- Ideally, if the chips are removed when the picker is open, it should stay open, and if the chips are removed when the picker is closed, it should probably stay closed… if that can't be achieved, I'm not sure which is better, always closing it or always opening it…? /@adrianschmidt

## Environment

- **lime-elements** version: 29.7.1
- Framework used: Can be reproduced in the docs

**Comment by adrianschmidt** [comment]
> 1. Clicking the x icon to the right (is it even needed at all?) makes it impossible to get the drop down to close again by clicking outside the drop down.

That's not good, and should be fixed.

> 2. Clicking to remove a selected signer while the drop down is opened just removes the text "Type to search..." and not the signer. You will have to click a second time to remove the signer.

Hmm… my first thought was that this would be because the dropdown is on top of a scrim, which catches the click and closes the menu, but that doesn't seem to be the case.

These are separate bugs though, so I'll split the second one into its own issue.

**Comment by FredrikWallstrom** [comment]
> These are separate bugs though, so I'll split the second one into its own issue.

Thx
