### ISSUE TITLE
limel-picker: clicking remove-button on chip when dropdown is open closes the picker but does not remove the chip (a bit annoying, but not a major problem)

### ISSUE THREAD

**Issue by adrianschmidt** [Lundalogik/lime-elements#1063]
## Current behavior

![pick](https://user-images.githubusercontent.com/58422324/105722815-58e91b80-5f26-11eb-9c4d-82f68e612b85.gif)

Clicking to remove a selected item while the drop down is open just closes the picker, does not remove the item. You will have to click a second time to remove the item. My first thought was that this is caused by a scrim catching the first click and closing the picker, but I checked and the picker doesn't use a scrim.

1. In a limel-picker that is configured with `multiple=true`, select an item
2. Open the dropdown again (you may have to click outside first, then on the picker again, this is a separate bug: #1064)
3. Hover the remove-button on the chip that was selected in step 1, note that it does indicate that it can be clicked:
   ![image](https://user-images.githubusercontent.com/154725/101471346-7e56a180-3947-11eb-874d-29a6da0b775e.png)
   Important! Use the remove-button on the chip, _not_ the one for removing all chips at once (again, separate bug concerning that one: #1062)
4. Click on the button

- The dropdown closes and the input is blurred, but the chip remains in the picker.

## Expected behavior

- The chip should be removed
- Ideally, if the chip is removed when the picker is open, it should stay open, and if the chip is removed when the picker is closed, it should probably stay closed… if that can't be achieved, I'm not sure which is better, always closing it or always opening it…?

## Environment

- **lime-elements** version: 29.8.0
- Framework used: Reproducible in the docs

Originally reported by @FredrikWallstrom

**Comment by hannahu** [comment]
This bug has been solved when fixing another issue
