### ISSUE TITLE
Icon button component affected by MDC Ripple bugs

### ISSUE THREAD

**Issue by anderssonjohan** [Lundalogik/lime-elements#1065]
## Current behavior

1. Focused state makes button look stuck

This makes a button look like this when it's being clicked.

![mdcripple-background-focused-sticky](https://user-images.githubusercontent.com/435885/101535333-c9e56b80-3998-11eb-94dc-c8c196cbf4b1.gif)

2. `:hover` is sticky on iOS so ripple never goes away until other element is focused

## Expected behavior

1. Focused state issue

Workaround: Remove CSS class manually in click handler

```javascript
onClick={(ev) => {
    const e: any = ev.currentTarget;
    const mdcButton = e.shadowRoot.querySelector('button');
    setTimeout(() => mdcButton.classList.remove('mdc-ripple-upgraded--background-focused'), 100);
}}
```

![mdcripple-background-focused-workaround](https://user-images.githubusercontent.com/435885/101535750-69a2f980-3999-11eb-87a4-e761ba9f0f31.gif)

This focused state behavior is not a feature in MDC on other platforms than MDC Web and is reported over and over in various places. In every place I've found it has been closed because of accessibility reasons.
https://github.com/material-components/material-components-web/issues/2337#issuecomment-370544239

This accessibility feature is of course important, but only if you have a device where you can tab around AND you tabbed to the element, ie. not clicked or used touch input.
The expected behavior should be something like this comment suggests:
https://github.com/material-components/material-components-web/issues/1951#issuecomment-359084163

Example of expected behavior using the Github comment linked above. The focused state only appears when the button is tabbed to, NOT when it's clicked using the pointer.

![focusstyle](https://user-images.githubusercontent.com/435885/101534100-fac4a100-3996-11eb-886c-c5889536af09.gif)

Suggested fix: Remove focused CSS class when button is clicked, not tabbed to

```typescript
@Listen('click')
private removeFocusedStateOnClick() {
    const mdcButton = this.host.shadowRoot.querySelector('.mdc-icon-button');
    mdcButton.classList.remove('mdc-ripple-upgraded--background-focused');
}
```

2. The sticky `:hover` state on iOS

When the workaround for the focused state is in place, the sticky ripple still exists on mobile devices.
This is due to the `:hover` state not being removed. Some very old references to this issue:
https://bugs.webkit.org/show_bug.cgi?id=158517

Using the workaround above but switching to iPhone simulation still shows the error, but using a slightly less intense ripple due to other fg-opacity in `.mdc-button:hover`:
![mdcripple-hover-state-sticky](https://user-images.githubusercontent.com/435885/101536393-3d3bad00-399a-11eb-9f28-824e5161e7b0.gif)
This means, we turn off the focused state style, but we can't remove the `:hover` state of the element.

Suggested fix: Use a media query to turn off the hover effect on non-mouse devices

```css
@media(pointer: coarse) {
    .mdc-icon-button:hover::before {
        opacity: 0.0;
    }
}
```
...which gives the expected result even on a touch device.
![mdcripple-hover-state-working](https://user-images.githubusercontent.com/435885/101537727-43cb2400-399c-11eb-85b2-450a64522b8e.gif)

References:
- https://dzone.com/articles/finally-a-css-only-solution-to-hover-on-touchscree 
- https://developer.mozilla.org/en-US/docs/Web/CSS/@media/pointer

## Environment

- **lime-elements** version: 29.8.0 
- Framework used: 
- Logs:

**Comment by adrianschmidt** [comment]
Wow, those seem to be some pretty nice workarounds for what's been very difficult problems to solve. Thank you!

So, with `@media(pointer: coarse)` reporting the _primary_ pointing device, I assume most laptops with both touchscreen and mouse pad would probably either report `fine` or switch between `fine` and `coarse` depending on which device was used last…? If so, that's what we've been needing to be able to make lime-elements work really well with both mobile devices and desktop devices.

Looks like Firefox was last of the big browsers to support this, and they've supported it for two years day after tomorrow (https://caniuse.com/css-media-interaction)… I can't believe I've not known about this for all this time 🤯🤦‍♂️

**Comment by Kiarokh** [comment]
This is awesome @anderssonjohan ! I love it! You're awesome dude!

Once I was playing around with this and it turned out that only Chrome has this behaviour with our icon buttons. Safari and Firefox were working fine. I never tested on iOS though. So I reported it as a bug to Chrome folks. (which never got fixed obviously, and there seems to be a reason for it as you mention 😄 )

It's great that there is a way to turn off the hover state on mobile devices. 

My only note is that:
1. Sometimes the hover state is helpful even on touchscreen devices. Usually when you play some sort of animation or interactive visual effect on hover > active. So we need to choose to use this wisely.
1. Some time ago, we discussed in the feature team to remove Material Design's ripple effect from Lime Elements. There are many reasons for it. But mostly because they do a lot of dirty💩 in the DOM and highjack `:before` and `:after` in the dom, which could be used for better things if it was up to us. 😄 But it doesn't mean that we shouldn't fix this now!!

Really great job Johan!

**Comment by anderssonjohan** [comment]
> Wow, those seem to be some pretty nice workarounds for what's been very difficult problems to solve. Thank you!
> 
> So, with `@media(pointer: coarse)` reporting the _primary_ pointing device, I assume most laptops with both touchscreen and mouse pad would probably either report `fine` or switch between `fine` and `coarse` depending on which device was used last…? If so, that's what we've been needing to be able to make lime-elements work really well with both mobile devices and desktop devices.
> 
> Looks like Firefox was last of the big browsers to support this, and they've supported it for two years day after tomorrow ([https://caniuse.com/css-media-interaction)…](https://caniuse.com/css-media-interaction)%E2%80%A6) I can't believe I've not known about this for all this time 🤯🤦‍♂️

My worry in this fix lies in picking the correct media query and making sure it works in all setups.
With that said, I have NOT tried anything else than using DevTools with Chrome on macOS.

Perhaps we can try this out with our Dell laptops with touchscreens.
Also, I don't know what happens if you connect a bluetooth mouse to an android tablet.. will primary still be `coarse` due to the touchscreen? `any-pointer` should report `fine` with the bluetooth mouse connected, but is that a case where we should enable hover effects? 
Here is a test page for `any-pointer`/`any-hover`: https://googlechrome.github.io/samples/media-hover-pointer/

**Comment by Kiarokh** [comment]
As a generic comment I'd say: losing the ripple effect ain't the whole world. But losing a proper visual feedback on `hover` is. On the other hand, we still have the `cursor: pointer;` thingy for icons buttons (which is a "proper visual feedback on `hover`). So, still safe it in some weird combination of touch and mouse the ripple animation doesn't play. Does it make sense?
