### ISSUE TITLE
limel-input: Labels are cut off

### ISSUE THREAD

**Issue by Kiarokh** [Lundalogik/lime-elements#1067]
![lables](https://user-images.githubusercontent.com/35954987/101483162-0e9ce280-3958-11eb-9373-027b41f4829b.gif)

As soon as the field gets `focus`, some code calculates an inline `width` and applies it to `<div class="mdc-notched-outline__notch">`. Then it recalculates the width, after you have typed something and clicked outside to remove the `focus`. I guess these issues are somehow related.

![image](https://user-images.githubusercontent.com/35954987/100744689-798d6d00-33de-11eb-9074-b6b8791657d2.png)

**Comment by eketorp** [comment]
Duplicate of #1739

**Comment by eketorp** [comment]
Duplicate of #1671
