### ISSUE TITLE
limel-button with icon isn't responsive

### ISSUE THREAD

**Issue by BregenzerK** [Lundalogik/lime-elements#1089]
## Current behavior

according to [this comment](https://github.com/Lundalogik/limepkg-esign/issues/548#issuecomment-738068262) we shouldn't use the button with an icon due to responsivness in a grid. 
In my opinion this is a feature `lime-elements` should really support, so we should either 
1. remove the icon property from the `limel-button` and create a specific component for that case or
2. fix the responsiveness problems in the `limel-button`

@Kiarokh can you please add some explanation here to understand the complexity? 

## Environment

- **lime-elements** version: 30.1.0

**Comment by adrianschmidt** [comment]
The responsiveness problems have already been fixed. You might have to set `display:block` on the `limel-button` element though, as it defaults to `display:inline-block`. Putting it in a grid or a flex-box probably accomplishes that too, without explicitly setting `display:block` (I _think_, not sure).

If you need the exact version of the fix, I can look it up.

**Comment by adrianschmidt** [comment]
After reading the comment, I don't think showing or not showing an icon has any bearing on whether the button works in a grid. I think @Kiarokh was just saying that limel-button shouldn't be used at all in that case. (Something which I'm not sure I agree with, but I haven't heard any arguments except for the responsiveness bug, and that's been fixed, as mentioned above.)

**Comment by BregenzerK** [comment]
It was all a misunderstanding. Kia wasn't clear enough in his comment. He wasn't talking about a button with icon and label but more complex cases like including a progress bar or several icon. I asked him to create an extra issue for those requirements.
