### ISSUE TITLE
limel-form can report as valid even though there are invalid components (and perhaps vice versa)

### ISSUE THREAD

**Issue by adrianschmidt** [Lundalogik/lime-elements#1111]
The Name field on Company is required, and when I empty that field, this works as expected. However, the Homepage field is not required, but does have validation, and when I make that invalid, it does not make the Save button disabled.

The problem is that when the form is validated, we never actually look at whether the _inputs_ consider themselves valid or invalid. We just validate against the schema we have…

I think that's going to be a problem, because it means that we can be out of synk between what the individual components consider valid, and what the form considers valid. And anyone writing a custom form component will have to write their validation twice, once for the component and once for the schema.

_Originally posted by @adrianschmidt in https://github.com/Lundalogik/lime-crm-components/pull/267#r564483307_

**Comment by adrianschmidt** [comment]
Ping @jgroth

**Comment by jgroth** [comment]
Hmm yeah, the form component only utilizes the `invalid` prop if I remember correctly, so all the standard input fields we have must comply to the status of that one I think :thinking: I guess this is somewhat related to the other discussion we had the other day when we noticed that for the input field it only works when you set it to `true`? :sweat_smile: 

I guess the `invalid` prop has three states but we probably only consider two of them. They are `true`, `false` and `undefined` :thinking:

**Comment by adrianschmidt** [comment]
As far as I can see, the form-validation doesn't ever look at the component or its property at all. The highlighted part in the screenshot does the validation, and that only compares the current values against the schema, and the line below it only formats the potential validation errors that the validator on the highlighted line has detected.

![image](https://user-images.githubusercontent.com/154725/105989803-e9983680-60a1-11eb-8afa-bdb7b7fa0ba2.png)
![image](https://user-images.githubusercontent.com/154725/105990057-4267cf00-60a2-11eb-812d-d07fedeaab8e.png)

That would be ok with me, but then all validation would have to be done according to what's defined in the schema, and that's not how it works currently, since we have native validation of some fields, and also the small amount of extra validation I added for `input[type=url]` in my PR. I imagine there may well be more complicated validation built in custom components in the future too…

**Comment by adrianschmidt** [comment]
I think we don't ever propagate the internal validity state outside each input component… there's no event for that in limel-input for example.

**Comment by adrianschmidt** [comment]
@maltja and I discussed this one, and came to the conclusion that we might never need this, and if we do, we should cross that bridge when we get to it. Instead, to solve the problem currently in front of us, we'll do #1128.

Thus, I'll close this.
