### ISSUE TITLE
limel-input-field with autocompletions: dropdown can only be closed by selecting an autocompletion

### ISSUE THREAD

**Issue by adrianschmidt** [Lundalogik/lime-elements#1115]
## Current behavior

https://user-images.githubusercontent.com/154725/106436343-474acb00-6474-11eb-9355-63ed42bc08ca.mov

1. Focus any limel-input-field with autocompletions.
2. Blur the element by clicking outside it, or tabbing away from it.

- The dropdown showing suggestions stays open.

## Expected behavior

The dropdown should close.

## Environment

- **lime-elements** version: v30.4.1
- Framework used: Can be reproduced in the _Input Field with Completions_ example in the docs
- Logs:

**Comment by adrianschmidt** [comment]
This doesn't seem to be using limel-menu-surface or limel-portal or popper in any way, which it probably should 😄

**Comment by eketorp** [comment]
Still there after today's release. Also expanding strangely in the viewport when doing the selection the second time

![ny person](https://user-images.githubusercontent.com/58422324/106945936-bcdec180-6728-11eb-89af-4fdd56ee2037.gif)

**Comment by adrianschmidt** [comment]
Yeah, we haven't touched this at all.

**Comment by adrianschmidt** [comment]
> expanding strangely in the viewport when doing the selection the second time

Not really. Since you already have "Dräng" in the field the second time, there are no other matching autocompletions, so the list is only one item long. If you empty the field, the dropdown should become taller again.

**Comment by eketorp** [comment]
> [...] there are no other matching autocompletions

Ah! I always thought of this as a text field with options. Not as autocompletion.
