### ISSUE TITLE
limel-file: cant reselect file after ignoring selection

### ISSUE THREAD

**Issue by sampsonbryce** [Lundalogik/lime-elements#1190]
## Current behavior

When doing something on the limel-file onChange event where you may want to reject the selected file (e.g. validating the file) you wont set the limel-file `value` prop. This leaves the file input empty, but if you try to reselect the file, the change event is never fired.

An example use case:
- Someone selects a file via the limel-file file picker
- The onChange function is called
- Some issues with the file are detected, but the user is given the choice to continue and ignore the issues, or cancel the file selection. 
    - If they cancel, the `value` prop is not updated
    - If they continue, the `value` prop is updated
- When the `value` prop is not updated, then the limel-file picker remains empty
- You cannot reselect the same file because the internal, underlying file picker thinks a file is already selected or something.

Steps to reproduce the behavior (i haven't run them but this should work):
```js
 @State
 private value = null;

 public render() {
   return <limel-file value={this.value} onChange={this.handleChange} />
 }

 private onChange(event) {
   if(window.confirm("Are you sure?")){
     this.value = { filename: event.detail.filename, id: event.detail.id }
   }
 }
```

## Expected behavior

If I don't update the `value` prop, then nothing is selected and i should be able to reselect the same file that was rejected before.

## Environment

- **lime-elements** version: 30.19.1
- Framework used: lime admin

**Comment by sampsonbryce** [comment]
This only seems to happen in chrome

**Comment by sampsonbryce** [comment]
I've solved this in the consumer, by setting a `key` prop on the limel-file component, and then incrementing the keys value every time the selected value is ignored so that the file component resets.

```js
 @State()
 private value = null;

 @State()
 private inputKey = 1;

 public render() {
   return <limel-file key={this.inputKey} value={this.value} onChange={this.handleChange} />
 }

 private onChange(event) {
   if(window.confirm("Are you sure?")){
     this.value = { filename: event.detail.filename, id: event.detail.id }
   }else{
     // Reset the file picker by rendering a totally new one
     this.inputKey += 1;
   }
 }

**Comment by sampsonbryce** [comment]
Just gonna leave this here for documentation:

File input components are always uncontrolled components because of their limited api behavior for security reasons. 

https://reactjs.org/docs/uncontrolled-components.html#the-file-input-tag
https://stackoverflow.com/questions/1696877/how-to-set-a-value-to-a-file-input-in-html

**Comment by adrianschmidt** [comment]
This seems like something we might want to either build into the component, or document as the "official" way to handle this…

What do you think?

**Comment by sampsonbryce** [comment]
I thought about maybe building it into the component, but its really up to the consumer to reject the file in the onChange handler, so i dont know how the limel-file would determine that. We could just reset the input element every time, but i just tried to increment a key on the input element and it doesn't seem to rerender when i do that so im not sure how we would go about deleteing and replacing it without doing some good ol fashioned delete element shenanigans. or flip a boolean really fast. 

I would probably just leave this to the user for now. Maybe revisit if it becomes an issue again later?

**Comment by adrianschmidt** [comment]
Yeah, leaving it up to the consumer seems to make sense. But then I think we could add it to the documentation in the form of an example. Kind of low prio though I guess… 🤷‍♂️
