### ISSUE TITLE
Required Inputfield of type number loses focus when emptied

### ISSUE THREAD

**Issue by lime-siry** [Lundalogik/lime-elements#1224]
## Current behavior

The issue occurs when you have an inputfield of type number that is required. 
When clearing the inputfield from numbers the browser drop focus on the field and I have to click the field again to be able to do inputs again

Go to [the documentation page](https://lundalogik.github.io/lime-elements/versions/31.4.0/#/component/limel-input-field/) and select inputfield of type number and make it a required field. Put in some numbers. 

![image](https://user-images.githubusercontent.com/69625404/116657544-e5283600-a98e-11eb-81c6-d4e775eec18c.png)

Remove the numbers and see the browser drop focus.

![image](https://user-images.githubusercontent.com/69625404/116657608-01c46e00-a98f-11eb-9969-e6d2235d736a.png)

Try to enter numbers and fail.

## Expected behavior

You should be able to clear the field without dropping focus so that the user can easily reenter a value if the messed up the initial input.

**Comment by adrianschmidt** [comment]
I've confirmed this bug. When the input-field is `required`, just typing a number and then pressing backspace to remove it triggers the bug. The bug does not appear when the input-field is _not_ `required`.

**Comment by Kiarokh** [comment]
unable to reproduce in the latest versions
