### ISSUE TITLE
limel-slider sometimes reports invalid when it shouldn't

### ISSUE THREAD

**Issue by adrianschmidt** [Lundalogik/lime-elements#1235]
## Current behavior

For a value of `0.30`, the slider is valid, as expected:
![image](https://user-images.githubusercontent.com/154725/117788629-d91e5d00-b247-11eb-9a2f-ef7eeaff101e.png)

But for a value of `0.29`, the slider is _invalid_:
![image](https://user-images.githubusercontent.com/154725/117788507-bdb35200-b247-11eb-9478-6463aebdbcfd.png)

1. Use a limel-slider with `step="0.01"` and `factor="100"` (the `factor` is probably irrelevant though)
2. Set the slider's value to `0.29` (visualised as `29` if using `factor="100"`).

- The slider reports as invalid with the message `"should be multiple of 0.01"`.

(The bug appears for values of `0.07`, `0.14`, `0.28`, `0.29`, `0.47`, `0.56`, `0.57`, `0.58`, `0.59`, and `0.94`.)

## Expected behavior

The slider should be valid for the given values. The bug is probably due to the way javascript handles decimals (losing precision).

## Environment

- **lime-elements** version: At least from v31.1.3 to latest `main`.
- Framework used: Can be reproduced in docs.
- Logs:

**Comment by Befkadu1** [comment]
This issue is fixed by the ajv-validator/ajv   [here](https://github.com/ajv-validator/ajv/blob/de021c4dbadc76e09a30ce145b03246ee533b414/docs/options.md#multipleofprecision)
