### ISSUE TITLE
Limel input: Text cursor jumps to end of input when rapidly typing

### ISSUE THREAD

**Issue by JohannesHansen** [Lundalogik/lime-elements#1255]
## Current behavior

When adding text in the middle of an existing string in the input field the cursor sometimes jumps to the end of the input.
This seems to happen when rapidly typing.

This behaviour is reproducable in the live docs, but also locally.

1. Add some text to an input field
2. Place the cursor at the beginning or middle of the text
3. Type really fast
4. Cursor will randomly jump to end of text

## Expected behavior
The cursor should not move unexpectedly.

## Environment

- **lime-elements** version: 31.10.0
- Framework used: StencilJS

**Comment by adrianschmidt** [comment]
I'm not sure if this is the same, but I think it probably is: We had problems in the web client that the input-fields were "laggy" and skipped characters when typing too fast. I think we still have the same problem in Lime Admin. I think we found a workaround for it, and if I recall correctly it was to debounce the updating of the value, but I don't remember the details. It definitely seems like something we need to find a proper fix for…

cc @jgroth

**Comment by jgroth** [comment]
> I'm not sure if this is the same, but I think it probably is: We had problems in the web client that the input-fields were "laggy" and skipped characters when typing too fast. I think we still have the same problem in Lime Admin. I think we found a workaround for it, and if I recall correctly it was to debounce the updating of the value, but I don't remember the details. It definitely seems like something we need to find a proper fix for…
> 
> cc @jgroth

Yeah I noticed the laggy input field just a few days ago I think, so it seems it has not yet been fixed completely. That was in the webclient, not lime-admin

**Comment by JohannesHansen** [comment]
@adrianschmidt I've tried debouncing the updates in React and unfortunately it doesn't seem to have an effect.
