### ISSUE TITLE
Need a good strategy for icons from icons8 which are used in the code

### ISSUE THREAD

**Issue by Kiarokh** [Lundalogik/lime-elements#1272]
## New feature motivation
But anyone using Lime Elements in an environment where lime-icons8 is not installed, will have to supply some other icons. They can do that of course, and to get any "hardcoded" icons to show up, they just need to make sure they add some icon in a file using the correct file name. 

An example of such icons in `input-field.tsx`:

````tsx
	private getTrailingIcon() {
        if (this.isInvalid()) {
            return 'high_importance';
        }

        if (this.trailingIcon) {
            return this.trailingIcon;
        }

        if (this.showLink && this.type === 'email') {
            return 'filled_message';
        }

        if (this.showLink && this.type === 'tel') {
            return 'phone';
        }

        if (
            this.showLink &&
            (this.type === 'url' || this.type === 'urlAsText')
        ) {
            return 'external_link';
        }
    }
````

## New feature description

We have two choices:

- Either add proper docs with filenames.
- Or design icons ourselves that can be redistributed with Lime Elements.

**Comment by adrianschmidt** [comment]
I swapped the label to `design`, since it seems like we're still more in the discuss-and-decide phase than the implement phase 🙂

**Comment by adrianschmidt** [comment]
Did we actually do something to complete this issue, or are you just tired of seeing it open? 😄

**Comment by Kiarokh** [comment]
I had a vague memory that this was not an issue anymore… 😅 we talked about it in some comment before. I don't rememebr the details. so I just got tired and closed this. :P

**Comment by adrianschmidt** [comment]
Fair enough 🙂
