### ISSUE TITLE
limel-file with limited accepted file types still allows any file type when dragging and dropping

### ISSUE THREAD

**Issue by adrianschmidt** [Lundalogik/lime-elements#1307]
## Current behavior

1. Go to the _Limit accepted file types_ example in the docs.
2. Drag and drop a document that is not a png or jpg.

- The document is attached.

## Expected behavior

The document should be rejected.

## Environment

- **lime-elements** version: v30.18.5, v33.0.2
- Framework used: reproducible in the docs
- Logs:

**Comment by civing** [comment]
> this is already fixed, right @civing ? 

Yes! This should be fixed in the latest refactor.
