### ISSUE TITLE
Snackbar: add z-index variable

### ISSUE THREAD

**Issue by anderssonjohan** [Lundalogik/lime-elements#1331]
## New feature motivation

When customizing the z-index of components such as the limel-dialog, showing a snackbar can place it beneath the dialog. To make the feature set consistent, the snackbar component should also have a z-index variable.

## New feature description

- [ ] allow customization of the MDC snackbar z-index property using a CSS variable
- [ ] update the docs with a value greater than the one of the dialog component

## New feature implementation

The index.html for the docs should probably be updated to contain the added `--snackbar-z-index` variable:

```
:root {
    --dialog-z-index: 110;
    --popover-z-index: 115;
    --dropdown-z-index: 120;
    --snackbar-z-index: 125;
}
```

Use the [Snackbar](https://material.io/components/snackbars/web#style-customization) z-index sass mixin to set it.

**Comment by Kiarokh** [comment]
Where to look for inspiration when implementing: https://github.com/Lundalogik/lime-elements/pull/1137/commits/4608bc9234fb9fb1f0bec197b283483878214744

**Comment by Kiarokh** [comment]
solved by https://github.com/Lundalogik/lime-elements/pull/3084
