### ISSUE TITLE
limel-progress-flow: FlowItem is not exported

### ISSUE THREAD

**Issue by DavidAkkerman** [Lundalogik/lime-elements#1338]
## Current behavior

I can't import FlowItem from lime-elements, I believe it's because it's not exported in the interface file.

1. Try to import FlowItem from '@limetech/lime-elements'

## Environment

- **lime-elements** version: 33.10.0

**Comment by adrianschmidt** [comment]
Hmm… the `FlowItem` interface is exported from the file where it's defined. The contents of that file might not be exported externally though. I'll have a look at it 👍
