### ISSUE TITLE
limel-picker: when emptying picker on iPhone, the picker becomes focused, but the on-screen keyboard does not appear

### ISSUE THREAD

**Issue by adrianschmidt** [Lundalogik/lime-elements#1344]
[Originally reported](https://limetech.workplace.com/groups/limecrm/permalink/3938882826216071/) by @maxneuman 

## Current behavior

1. On an iPhone, open a deal with a sales rep attached.
2. Press the x on the chip.
3. Click in the empty space to start typing but the keyboard on the phone doesn't appear.

![image](https://user-images.githubusercontent.com/154725/132343977-e3439ced-c0f7-46fe-bf79-ceada203627c.png)

## Expected behavior

Either keyboard och a drop down of my colleagues. It worked again if I left the app and went in again after some frenetic scrolling 🙂

## Environment

- **lime-elements** version: 
- Framework used: Reproducible in the docs.
- Logs:

**Comment by adrianschmidt** [comment]
Hmm… 🤔

Why do we even want to focus the input when a chip has been removed by _clicking_ the remove button? We already have the functionality that you can have the input focused, and press backspace to select and then remove a chip. When you do that, the focus stays on the input, and the dropdown stays visible, or appears if it wasn't already visible.

When a user clicks the remove button, they're not using the keyboard to navigate and perform that action—they're either using a mouse or a touchscreen… why do we assume that one will want to focus the input and open the dropdown in those cases? If the user wants to add another object instead of the one just removed, they can just as easily tap on the input-field again. If they don't want to add another object, having the dropdown open is just annoying, especially on mobile, where the dropdown usually covers most of the screen…

Ping @Kiarokh @LucyChyzhova @blombergedvin for thoughts…

**Comment by adrianschmidt** [comment]
Ping @jgroth too for thoughts 🙂

**Comment by adrianschmidt** [comment]
_Much_ simpler alternative solution added ☝️

**Comment by Kiarokh** [comment]
I think your latest solution is great @adrianschmidt 
I'm not sure how critical it is to be able to type or see the suggestions list, directly after removing a chip. However, one tap/click to activate the field again seems to be fair enough.
