### ISSUE TITLE
Empty table message is not centered and sometimes requires a resize of the table to be visible on small screens

### ISSUE THREAD

**Issue by maltja** [Lundalogik/lime-elements#1346]
I created the issue here instead and closed the one in crm-feature https://github.com/Lundalogik/crm-feature/issues/2299

## Current behavior

On small screens the empty table message is not centered. And on really small screens like a phone it is not even visible because it too much to the right. 

https://user-images.githubusercontent.com/19202946/132519236-ddb63a5d-e8e8-458f-8696-d19f26ade542.mov

And when the table is empty it sometimes needs to be resized for the empty message to be rendered. 

https://user-images.githubusercontent.com/19202946/132519249-a5c45011-2e6b-4a56-953c-d9c28eeb6015.mov

## Expected behavior

The empty table message should be centered and always rendered when the table is empty.

## Environment

- **lime-elements** version: v33.11.1-next.1

**Comment by Kiarokh** [comment]
I think this is fixed
