### ISSUE TITLE
limel-button: support dark mode

### ISSUE THREAD

**Issue by adrianschmidt** [Lundalogik/lime-elements#1372]
- [ ] Non-primary button stays light in dark mode:
	![image](https://user-images.githubusercontent.com/154725/135596402-42abb904-9ffd-45e6-9ded-34bcdc378e40.png)

- [ ] Disabled button "disappears"
	![image](https://user-images.githubusercontent.com/154725/135598154-bb3c7e45-d605-4b3b-af9f-0d6847bbe4b9.png)

**Comment by maxneuman** [comment]
Can we prioritize these three issues during the summer? :) Would be awesome to deploy a dark mode version of Lime Go (and all our other products!) after the vacations.
