### ISSUE TITLE
limel-button-group: support dark mode

### ISSUE THREAD

**Issue by adrianschmidt** [Lundalogik/lime-elements#1373]
The component stays light in dark mode:

![image](https://user-images.githubusercontent.com/154725/135598863-91d2fb6f-9e40-4ee9-b3f3-e736296b9178.png)

**Comment by maxneuman** [comment]
Can we prioritize these three issues during the summer? :) Would be awesome to deploy a dark mode version of Lime Go (and all our other products!)
