### ISSUE TITLE
limel-checkbox: support dark mode

### ISSUE THREAD

**Issue by adrianschmidt** [Lundalogik/lime-elements#1374]
- [ ] remains dark, so almost disappears in dark mode:
	![image](https://user-images.githubusercontent.com/154725/135620256-3e47116c-92ee-4c4a-b249-b59441deaccc.png)

**Comment by maxneuman** [comment]
Can we prioritize these three issues during the summer? :) Would be awesome to deploy a dark mode version of Lime Go (and all our other products!)
