### ISSUE TITLE
Dialog: Button slot content not always rendered

### ISSUE THREAD

**Issue by JohannesHansen** [Lundalogik/lime-elements#1375]
## Current behavior
The bottom button slot area in dialogs doesn't always render. Typically the area will be hidden the first time a specific dialog is opened, but will appear the second time. This is a bit odd as we unmount the entire dialog component between opens, so it should be a "fresh" dialog each time.

The issue seem to happen quite concistently when used in React. Rendering the dialog as open or closed initially does not seem to have an impact, neither does triggering a content rerender.

The correct markup appears in the DOM, but the buttons doesn't appear in the dialog footer nor in the dialog body.
![image](https://user-images.githubusercontent.com/3470434/135648175-494ab0c2-0c88-4b32-a8fe-c475dc81464c.png)

## Expected behavior
The content of the button slot should be consistenly rendered at the bottom of the dialog.

## Environment

- **lime-elements** version: 33.12.0
- Framework used: React
- Logs: No errors or warnings appear

**Comment by adrianschmidt** [comment]
Crap…

I'm guessing this has something to do with #1022 😞
