### ISSUE TITLE
Datepicker: Highlight current date

### ISSUE THREAD

**Issue by JohannesHansen** [Lundalogik/lime-elements#1380]
## New feature motivation

When you open the date picker with no predefined date value, the current date will be softly highlighted in the calendar. As soon as an other date is selected this highlight disappears.

Lime Go is getting frequent requests from users to visually mark the current date. Quickly being able to spot "today" would increase usability.

## New feature description

The current date in the date picker is always highlightet, or in some way indicated to make it easy to spot.

**Comment by Kiarokh** [comment]
fixed since long time ago
