### ISSUE TITLE
Limel-select: Allow the user to search for options using keyboard input

### ISSUE THREAD

**Issue by blombergedvin** [Lundalogik/lime-elements#1424]
## New feature motivation
In the past cycle we added the possibility to search for objects in limel-menu using the keyboard, such as typing C to get to companies. This would be great to be able to do in limel-select aswell. Mainly in combination with the configuration of cards in Lime Admin. 

## New feature description

Enable keyboard input when a limel-select is open, highlight option that matches the input.

**Comment by jensgustafsson** [comment]
It seems like there's no built-in support for this in MDC. I suggest that we close this

**Comment by adrianschmidt** [comment]
`mdc-select` seems to have some support for typeahead (which is what the feature is called, for reasons unknown to me). [MDCSelectAdapter ](https://github.com/material-components/material-components-web/tree/v11.0.0/packages/mdc-select#mdcselectadapter) has a method called `isTypeaheadInProgress`.
