### ISSUE TITLE
"Navigate to link"-icon covers text on input fields of type url if `readonly=true`

### ISSUE THREAD

**Issue by eketorp** [Lundalogik/lime-elements#1480]
## Current behavior

In CRM:
![image](https://user-images.githubusercontent.com/58422324/144628779-aadd808e-35ce-434b-99f9-b47217ab2827.png)

In lime element docs:
![image](https://user-images.githubusercontent.com/58422324/144628824-5ce27c8e-1c43-4609-a71b-cfda61abcfa3.png)

1. Enter a long text
2. Set field to readonly

## Expected behavior

Icon should maybe have some background?

## Environment

- **lime-elements** version: 34.0.1
- Framework used: 
- Logs:

**Comment by adrianschmidt** [comment]
Screenshots from `v34.1.0-next.11`:

Editable:
![image](https://user-images.githubusercontent.com/154725/144813296-ba883f65-68cf-488b-bd1f-af0182572896.png)

Readonly:
![image](https://user-images.githubusercontent.com/154725/144813398-2dc2b6c1-819b-4d6b-a8ed-4b8ecd3480b5.png)

Readonly hovered:
![image](https://user-images.githubusercontent.com/154725/144813409-0cbb3610-db9b-4c56-9477-a3eeedd932a8.png)
