### ISSUE TITLE
date-picker: `format` property doesn't work as documented when date-picker is used inside limel-form

### ISSUE THREAD

**Issue by adrianschmidt** [Lundalogik/lime-elements#1489]
[Originally reported](https://forum.lime-crm.com/t/show-date-only-in-date-picker-in-web-component-schema/4141) by @amandaolsson.

## Current behavior

![image](https://user-images.githubusercontent.com/154725/145175544-b819b2af-47e6-48ed-880d-106012ee5657.png)

1. It's already reproduced for you, right in the first example of the docs for `limel-form`: https://lundalogik.github.io/lime-elements/versions/next/#/component/limel-form/

## Expected behavior

- ***Either*** the configuration is correct, and the date-picker should only display a date
- ***or***, the configuration is incorrect and should be fixed (I'm thinking maybe `format` has to be set on `lime.component.props`?)

## Environment

- **lime-elements** version: Verified in `v34.1.0-next.18` and `v32.4.4` (latest version before we updated MDC).
- Framework used: Reproducible in the docs.
- Logs:

**Comment by jgroth** [comment]
I have been having some discussions with @erikmangsten who also have been running into this issue

When generating a schema in Python there are three fields that can be used, shown in the example below

```py
class MySchema(Schema):
    datetime = fields.DateTime()
    date = fields.Date()
    time = fields.Time()
```

Which will generate something like following JSON schema 

```json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "definitions": {
        "MySchema": {
            "properties": {
                "date": {
                    "title": "Date",
                    "type": "string",
                    "format": "date"
                },
                "time": {
                    "title": "Time",
                    "type": "string",
                    "format": "time"
                },
                "datetime": {
                    "title": "DateTime",
                    "type": "string",
                    "format": "date-time"
                }
            },
            "type": "object",
            "dependencies": {},
            "additionalProperties": false
        }
    },
    "$ref": "#/definitions/MySchema"
}
```

When `format` is set to either `date` or `date-time` the picker will show up, but `date` will still display the time which is incorrect. When `format` is set to `time` the picker does not show up at all.

We probably have to make sure that we set the correct `type` on the picker as @adrianschmidt mentioned above

**Comment by Kiarokh** [comment]
I found these old PRs in cycle 20. Not sure why they're left there. But if they don't need to be fixed, it's better to close them. So I just move this to Cooldown's review column

**Comment by vicgeralds** [comment]
> I found these old PRs in cycle 20. Not sure why they're left there. But if they don't need to be fixed, it's better to close them. So I just move this to Cooldown's review column

Because no one had time to review them I guess. If I remember correctly, this one is not really needed in CRM, where we always use `date-time` format (and `limebb-date-picker`). That doesn't mean this bug don't need to be fixed, if we care about others using lime-elements.
