### ISSUE TITLE
build: only run publish docs once in the workflows

### ISSUE THREAD

**Issue by anderssonjohan** [Lundalogik/lime-elements#1534]
When a PR workflow is running, we build the docs both in the CI job and the Publish Docs job, but why?
In this run, the CI job took 2 min extra in the end to build the docs, even though the Publish Docs job already was completed:
![Screen Shot 2022-01-31 at 18 53 13](https://user-images.githubusercontent.com/435885/151946629-4ce85ea0-cb6e-4d6a-a8aa-113d1648ac4f.png)

If [this command](https://github.com/Lundalogik/lime-elements/blob/6cffc5824f69ec92a852482bc24020f084124b7c/.github/workflows/pr-checks.yml#L88) publishes the PR version of the docs, perhaps we should only run [the CI job docs build](https://github.com/Lundalogik/lime-elements/blob/6cffc5824f69ec92a852482bc24020f084124b7c/.github/workflows/pr-checks.yml#L43) when commits are pushed to `main` and `next` (using an `if:`)?

**Comment by adrianschmidt** [comment]
> If this command publishes the PR version of the docs, perhaps we should only run the CI job docs build when commits are pushed to main and next (using an if:)?

The PR-checks workflow doesn't run at all in `next` and `main`. We have a separate workflow file for that.

(I've never liked the "all-in-one with loads and loads of if:s" workflow style that seems so popular with all the other teams. I find it annoying to always have to remember to look for the `if` to check in which cases a particular job is actually run, and it becomes very confusing when I _inevitably_ forget… 😖 — I also don't feel comfortable when accidentally running production jobs on a dev branch is constantly just a typo away… 😬)

**Comment by adrianschmidt** [comment]
This was fixed in #1563
