### ISSUE TITLE
limel-select: After selecting an option, keyboard navigation usually doesn't "reach" all options

### ISSUE THREAD

**Issue by adrianschmidt** [Lundalogik/lime-elements#1537]
## Current behavior

https://user-images.githubusercontent.com/154725/152160777-253d2243-1593-44b4-93b5-b89304ab5aa8.mov

1. Go to the [docs for limel-select](https://lundalogik.github.io/lime-elements/versions/next/#/component/limel-select/).
2. Open a limel-select component, either by tabbing to it and hitting enter, or by clicking on it.
3. Select an option.
4. Open the same select again.
5. Try to navigate up and down through all the options using the up and down arrow keys.
6. If all options can be focused, try selecting a different option, and repeat from step 4.

- You'll soon end up in some state where only some of the options can be focused using the arrow keys. Sometimes the focus can't be moved at all.

## Expected behavior

It should always be possible to move the focus around between all options.

## Environment

- **lime-elements** version: 35.0.0-next.3, but has existed for quite a while
- Framework used: Reproducible in the docs
- Logs:

**Comment by Kiarokh** [comment]
this is fixed
