### ISSUE TITLE
limel-select, multiple=true. First option always highlights when clicking any option.

### ISSUE THREAD

**Issue by RasmusHeitmann** [Lundalogik/lime-elements#1573]
## Current behavior

The first option always lights up when clicking any option in a multiple select field. 
![Animation](https://user-images.githubusercontent.com/88432315/152959255-3186732f-b0c4-4daf-bec7-9de16f84548a.gif)

1. Open select field.
2. Choose any option that is not the first option.
3. See the first option light up.

## Expected behavior

It should only be the option clicked that lights up. 

## Environment

- **lime-elements** version: 34.1.0 (example is from https://lundalogik.github.io/lime-elements/versions/34.1.0/#/)
- Framework used: Reproducible in docs
- Logs:

**Comment by adrianschmidt** [comment]
I'm guessing this has the same underlying cause as #1268.

**Comment by Kiarokh** [comment]
not there anymore
