### ISSUE TITLE
List: error is thrown when deselecting an item in list of type radio

### ISSUE THREAD

**Issue by FredrikWallstrom** [Lundalogik/lime-elements#1593]
## Current behavior
An error is thrown if we are setting `mdcList.selectedIndex` to -1. This happens when we are refreshing the list and there is no item selected, so to reproduce, you can just deselect an item in the list. Also reproduceable in lime-elements docs.

This only happens when the list is **not** of type multiple, i.e `radio` or `selectable`.

I created a PR for this a while ago where I'm not setting the `selectedIndex` if no item is selected. Not sure though if that is the correct solution, maybe we want to destroy the component and recreate it instead. Here is the PR: https://github.com/Lundalogik/lime-elements/pull/1504

1. Go to lime-elements docs and deselect an item of list type `radio`.

## Expected behavior

No errors should be thrown.

**Comment by adrianschmidt** [comment]
Ah! This is actually a bug in MDC. We'll add a workaround, but I'll open a bug issue in MDC too, if there isn't one already.

**Comment by adrianschmidt** [comment]
Ah, the current MDCList is deprecated, an they're working on a replacement, but the spec for that is apparently only a draft so far. So I won't actually bother reporting this bug to them. We've got a good workaround now anyway 👍
