### ISSUE TITLE
limel-form: calculation of columns only on resize wrong initial value

### ISSUE THREAD

**Issue by TommyLindh2** [Lundalogik/lime-elements#1628]
## Current behavior

When having a `limel-form` with layout grid the calculation of number of columns seems off and is "corrected" if the size of the form is resized.

It looks like it's [here](https://github.com/Lundalogik/lime-elements/blob/e5cff57c076efe832f60e0af960ae9a1474fd8d0/src/components/form/templates/grid-layout.ts#L33-L51)

The initial width is `35rem` and then it's single column view which makes my two fields on separate rows.
But when changing the width to `34rem` and then back to `35rem` the two fields are on the same row (Which is the wanted behavior)

See how it behaves below:

https://user-images.githubusercontent.com/154725/156997308-d52e60e6-5e5e-4c13-bf96-ad6784da951b.mov

(I made a video of the gif, [original gif here](https://user-images.githubusercontent.com/1814702/154678468-858e5d55-5fea-4e85-b9ea-2051881be17c.gif) / @adrianschmidt)

FormSchema:
```typescript
{
    type: 'object',
    required: ['note'],
    lime: {
        layout: {
            type: 'grid',
            columns: 2,
        },
    },
    properties: {
        person: {
            title: 'Person',
            readOnly: true,
            lime: {
                layout: {
                    colSpan: 1,
                },
            },
        },
        company: {
            title: 'Company',
            readOnly: true,
            lime: {
                layout: {
                    colSpan: 1,
                },
            },
        },
        note: {
            title: 'Note',
            lime: {
                layout: {
                    colSpan: 'all',
                }
            }
        }    
    }
};
```

Render it inside a `limel-dialog` and set the `--dialog-width` to for instance `35rem`

## Expected behavior

It should get the same number of columns initially and after a resize-event.
In this case 2 columns.

## Environment

- **lime-elements** version: 35.0.0-next.9

**Comment by TommyLindh2** [comment]
@BjornOstberg if you want to follow this.

**Comment by adrianschmidt** [comment]
Hmm… that's odd… 🤔

@Kiarokh Do you have any idea what could cause this?

@TommyLindh2 FYI, nowadays, GitHub supports uploading videos, as well as gifs, and videos have the benefit of having playback controls 🙂

**Comment by BjornOstberg** [comment]
@Kiarokh I think I can share and show on monday if that fits your schedule?

**Comment by Kiarokh** [comment]
Absolutely

**Comment by Kiarokh** [comment]
Seems like content of the dialog which are in the DOM have no initial width, since the container has display: none; when it's loaded. So limel-form thinks that there is no space for more than one column, and decides to put a 1 column layout, on the grid.

https://user-images.githubusercontent.com/35954987/154981978-b04f6b24-342f-4331-9069-5fd576545307.mov

We tested writing an initial width for the limel-form as an inline style. But that didn't help. Any ideas @adrianschmidt ?

**Comment by adrianschmidt** [comment]
I think the dialog emits a `resize` event after it has been opened. Listen to that and check the width when the event is received, then a width ought to have been set.

**Comment by adrianschmidt** [comment]
`document.addEventListener('resize', (event) => { yada yada });`

**Comment by adrianschmidt** [comment]
Oh, and remember to remove the event listener when the component is removed too!

**Comment by TommyLindh2** [comment]
@adrianschmidt Isn't this something that you can try and depending on result do a fix or not.
Otherswise we will just go back and forth and waste a lot of each others time.

Or are you suggesting that as a work-around?

**Comment by adrianschmidt** [comment]
Ah, sorry, you're right, this seems like something we should fix in limel-form. If the problem is what I think it is, it should be easy (and thus quick) to fix 👍

**Comment by adrianschmidt** [comment]
I got annoyed with not being able to pause the gif, so I screen captured a video of it and replaced the gif with that 😁

**Comment by TommyLindh2** [comment]
> I got annoyed with not being able to pause the gif, so I screen captured a video of it and replaced the gif with that 😁

I will totally use the video feature next time 😊

**Comment by LucyChyzhova** [comment]
We faced the same/similar problem in the CPQ project 

https://user-images.githubusercontent.com/50618208/212048919-4fff0022-8147-4436-94b0-64a1f9b1b858.mov

**Comment by adrianschmidt** [comment]
Is it possible to reproduce this in the docs, or in dev-feature or some other solution where I can play around with it. I'm somewhat ashamed to say, but I don't have time to figure out how to follow the steps to reproduce in the description.

**Comment by TommyLindh2** [comment]
> Is it possible to reproduce this in the docs, or in dev-feature or some other solution where I can play around with it. I'm somewhat ashamed to say, but I don't have time to figure out how to follow the steps to reproduce in the description.

I tried it locally in the lime-elements docs by changing the `src\components\dialog\examples\dialog-form.tsx` example to use limel-form, and that works to reproduce this error.

1. Add Style file `dialog-form.scss` to the examples folder of the dialog
   ```scss
    :host(limel-example-dialog-form) {
        .registration-dialog {
            --dialog-width: 35rem;
        }
    }
   ```
2. Replace the example `dialog-form.tsx` to the following:
    ```tsx
    import {
        FormSchema,
        LimelFormCustomEvent,
        ValidationStatus,
    } from '@limetech/lime-elements';
    import { Component, h, State } from '@stencil/core';

    const MIN_NAME_LENGTH = 5;
    const MIN_AGE = 20;
    const MAX_AGE = 50;

    interface FormValue {
        name: string;
        age: number;
        percentage: number;
    }

    /**
     * Dialog with form and header
     */
    @Component({
        tag: 'limel-example-dialog-form',
        styleUrl: 'dialog-form.scss',
        shadow: true,
    })
    export class DialogFormExample {
        @State()
        private isOpen = false;

        @State()
        private isFormValid = false;

        @State()
        private formValue: FormValue;

        @State()
        private isConfirmationOpen = false;

        private formSchema: FormSchema<FormValue> = {
            type: 'object',
            lime: {
                layout: {
                    type: 'grid',
                    columns: 2,
                },
            },
            properties: {
                name: {
                    type: 'string',
                    title: 'Name',
                    minLength: MIN_NAME_LENGTH,
                },
                age: {
                    type: 'number',
                    title: 'Age',
                    minimum: MIN_AGE,
                    maximum: MAX_AGE,
                },
                percentage: {
                    type: 'number',
                    title: 'Percentage',
                    lime: {
                        layout: {
                            colSpan: 'all',
                        },
                        component: {
                            name: 'limel-slider',
                            props: {
                                unit: '%',
                            },
                        },
                    },
                },
            },
        };

        public render() {
            return [
                <limel-button
                    primary={true}
                    label="Open"
                    onClick={this.openDialog}
                />,
                <limel-dialog
                    class="registration-dialog"
                    heading="Registration"
                    open={this.isOpen}
                    onClose={this.closeDialog}
                    onClosing={this.onClosing}
                >
                    <limel-form
                        value={this.formValue}
                        schema={this.formSchema}
                        onChange={this.handleFormChange}
                        onValidate={this.handleFormValidation}
                    />
                    <limel-button
                        label="Cancel"
                        onClick={this.closeDialog}
                        slot="button"
                    />
                    <limel-button
                        primary={true}
                        label="Save"
                        disabled={!this.isFormValid}
                        onClick={this.submitForm}
                        slot="button"
                    />
                </limel-dialog>,
                <limel-dialog
                    open={this.isConfirmationOpen}
                    onClose={this.closeConfirmation}
                >
                    <p>Are you sure you want to close this? </p>
                    <limel-button
                        label="No"
                        onClick={this.onConfirmNegative}
                        slot="button"
                    />
                    <limel-button
                        label="Yes"
                        onClick={this.onConfirmPositive}
                        slot="button"
                    />
                </limel-dialog>,
            ];
        }

        private handleFormChange = (event: LimelFormCustomEvent<FormValue>) => {
            this.formValue = event.detail;
        };

        private handleFormValidation = (
            event: LimelFormCustomEvent<ValidationStatus>,
        ) => {
            this.isFormValid = event.detail.valid;
        };

        private submitForm = () => {
            alert(`${this.formValue?.name} is ${this.formValue?.age} years old`);
            this.closeDialog();
        };

        private openDialog = () => {
            this.isOpen = true;
        };

        private closeDialog = () => {
            this.isOpen = false;
        };

        private onClosing = () => {
            console.log('dialog is closing now!');
            this.isConfirmationOpen = true;
        };

        private closeConfirmation = () => {
            this.isConfirmationOpen = false;
        };

        private onConfirmPositive = () => {
            this.isConfirmationOpen = false;
            this.isOpen = false;
        };

        private onConfirmNegative = () => {
            this.isOpen = true;
            this.isConfirmationOpen = false;
        };
    }

    ```
