### ISSUE TITLE
limel-file only recognizes lowercase file extensions

### ISSUE THREAD

**Issue by dorisenthecat** [Lundalogik/lime-elements#1668]
## Current behavior

1. Go to https://lundalogik.github.io/lime-elements/versions/NEXT-35.0.0-next.31/#/component/limel-file/
2. In the basic example remove the attached file
3. Attach a word file with capital letters in the file extension (`.DOCX`)

![image](https://user-images.githubusercontent.com/1199682/157819410-bd8c7163-45a0-4477-8b16-9182e48bfd9e.png)

## Expected behavior

The word icon should also be shown for files with extension `.DOCX`.

## Environment

- **lime-elements** version: 35.0.0-next.31
- Framework used: 
- Logs:

**Comment by adrianschmidt** [comment]
This seems like it should be exceedingly easy to fix. PRs very much welcome!

**Comment by adrianschmidt** [comment]
In fact, something like this ought to solve it (not checked for possible errors if `extension` has a weird value):

```diff
- return filetypeIconTable[extension] || DEFAULT_ICON;
+ return filetypeIconTable[extension?.toLowerCase()] || DEFAULT_ICON;
```

https://github.com/Lundalogik/lime-elements/blob/cfb1ea6bcb27a65a048389fbe71aeadc57200990/src/components/file/icons.ts#L128
