### ISSUE TITLE
Display week number in the calendar

### ISSUE THREAD

**Issue by maxneuman** [Lundalogik/lime-elements#1766]
## New feature motivation

Display weeek number in the calendar 
Benefits: Not having to check own calendar, smooth workflow and increased value
![image](https://user-images.githubusercontent.com/84496681/169866921-8d2d2350-cd94-495c-94f4-d810a7e46af3.png)

## New feature description

______

**Comment by olssoncharlie** [comment]
This isn't a lime elements calendar, it's our own calendar in Go, so I'm taking the liberty to close it :)
