### ISSUE TITLE
visualize disabled steps of progress flow better

### ISSUE THREAD

**Issue by Kiarokh** [Lundalogik/lime-elements#1770]
![image](https://user-images.githubusercontent.com/35954987/171864597-4e1e8009-cc6b-4b4e-9135-937525c3e316.png)

Using transparency is not a good way to visualize a disabled step.

**Comment by adrianschmidt** [comment]
If we want to have something that works in most cases without having to either supply a secondary colour value for disabled, or calculating such a value from the given value, adding a semitransparent layer on top of the "buttons" might work. But you might already have some better idea in mind 😄

**Comment by Kiarokh** [comment]
Updated the post with a picture. I had copied in from Microsoft Edge,
![image](https://user-images.githubusercontent.com/35954987/171864904-9b35a3f6-14da-4e66-aeac-0af93f641a94.png)
😠 and to no surprise the freaking thing did not copy the image of course. So I had pasted the linek which was in the clipboard, instead of the image. 😄 

Thanks for the feedback Adrian. I have some ideas. But I'll sketch a bit first.

**Comment by Kiarokh** [comment]
I've had a look. This is quite hard to fix, without applying too many changes unfortunately. I might take it up again during the summer.

**Comment by Kiarokh** [comment]
The easiest fix would be using css filters, however when you apply a filter to something that has no z-index specified, it will mess around with the stacking context. So for example a disabled step with a filter of `filter: saturate(15%);` will go below the surrounding steps and its arrow will be covered by them. This would require us to apply z-index inline on each step, and it should be the reverse of their `index` in the dom. So the first step should get the highest z-index, and so forth.

Another solution might be us finding a better way to visualize a disabled step.

or adding background divs which can get the background color, and the filter on them. But these would require many changes in test files and styles

**Comment by Kiarokh** [comment]
I also tried using `clip-path` for instance `clip-path: polygon(0% 0%, calc(100% - 16px) 0%, 100% 50%, calc(100% - 16px) 100%, 0% 100%);` on the step or the divider. But that also fails us, since we need the divider lines between the steps, and that's hard to get when the elements are masked.

## About the linked PR:

I'd argue that the best way to address this is to avoid transparency on disabled steps for now. It's enough that the disabled steps have a `cursor: not-allowed` and get no shadow effect. 
To give a more clear signal to users, I also added a lock icon for disabled steps.

Selected and disabled 👇 
<img width="1061" alt="image" src="https://user-images.githubusercontent.com/35954987/191002207-8c70a550-8176-4c41-bb42-1d8418698f78.png">

All steps disabled, except first:
<img width="1051" alt="image" src="https://user-images.githubusercontent.com/35954987/191002345-7cbfdd40-6e4d-45af-8da0-4858d81c13d3.png">

**Comment by Kiarokh** [comment]
@joelricci FYI

**Comment by adrianschmidt** [comment]
> Selected and disabled 👇 <img alt="image" width="1061" src="https://user-images.githubusercontent.com/35954987/191002207-8c70a550-8176-4c41-bb42-1d8418698f78.png">
> 
> All steps disabled, except first: <img alt="image" width="1051" src="https://user-images.githubusercontent.com/35954987/191002345-7cbfdd40-6e4d-45af-8da0-4858d81c13d3.png">

If possible, I think it would both look better and be much clearer, if the step that is selected and disabled, had a white padlock icon on the normal green background. But maybe that doesn't work for all background colours?

**Comment by adrianschmidt** [comment]
Forgot to say: Overall, the update looks _fantastic_! Sooo much better than before! 😍

**Comment by Kiarokh** [comment]
Thanks Adrian. We must visualize each state differently. So selected must have its own visualization, and disabled its own. And they must be able to coexist. So we can't switch the color of the icon, to say this is now "selected" but "disabled". 

On top of that, we can't rely on colors to communicate meaning for a ton of reasons.

Any strategy that we can come up with that is aligned with the above is welcome 🤗

**Comment by adrianschmidt** [comment]
I never meant that the colour should communicate any meaning, I just meant that the colour should make it possible to _see_ 😅

I meant that it would be easier to see, and therefore easier to understand, if it looked something like this:

![image](https://user-images.githubusercontent.com/154725/193056569-acfb4e52-b068-4911-86f5-7796ab9bc705.png)
