### ISSUE TITLE
textarea: when `readonly` looks weird

### ISSUE THREAD

**Issue by LucyChyzhova** [Lundalogik/lime-elements#1848]
## Current behavior
<img width="1075" alt="Screenshot 2022-09-30 at 16 24 49" src="https://user-images.githubusercontent.com/50618208/193291817-989ea88e-6e0b-434e-b13f-9e05ccb69ba7.png">

1. …

## Environment

- **lime-elements** version: 
- Framework used: 
- Logs:

**Comment by Kiarokh** [comment]
didn't we fix this @LucyChyzhova ?

**Comment by LucyChyzhova** [comment]
yes, it is fixed here https://github.com/Lundalogik/lime-elements/pull/1884

I will close this issue
