### ISSUE TITLE
INput field: Big `prefix` overlaps with value

### ISSUE THREAD

**Issue by Kiarokh** [Lundalogik/lime-elements#1870]
## Current behavior

<img width="560" alt="image" src="https://user-images.githubusercontent.com/35954987/195379543-70d9f92f-3cd3-44fd-bd32-137618968eef.png">

## Environment

- **lime-elements** version: 
- Framework used: 
- Logs:

**Comment by Aksa12** [comment]
@Kiarokh can I work on this issue?

**Comment by Kiarokh** [comment]
Of course. You don't have to ask @Aksa12 ! Thanks for doing this. I saw that you've already connected a PR. We will look at it soon
