### ISSUE TITLE
Radio button component

### ISSUE THREAD

**Issue by olssoncharlie** [Lundalogik/lime-elements#1879]
## New feature motivation

Today you have to use Limel-list if we want to use radio buttons. Having to use a full List component to just render 1 or 2 radiobuttons doesn't make sense since this is limiting in terms of functionality and design choices since we become bound to the limel-list design. 

## New feature description

Break out the radio-button to a freestanding input component, like the limel-checkbox.

**Comment by Kiarokh** [comment]
Duplicated of https://github.com/Lundalogik/lime-elements/issues/1437
