### ISSUE TITLE
Badge: docs for CSS pros are missing 

### ISSUE THREAD

**Issue by Kiarokh** [Lundalogik/lime-elements#1901]
docs for CSS pros are missing 
<img width="502" alt="image" src="https://user-images.githubusercontent.com/35954987/197515441-ad566718-5aaa-412d-b56e-f12bf9ccc412.png">

**Comment by adrianschmidt** [comment]
I'm sure you've intended this as a reminder to yourself, but please elaborate at least a little in the description, so the rest of us can understand what the issue is about! 🙏😊

**Comment by adrianschmidt** [comment]
Ah! CSS _props_! Of course! 🤦‍♂️🤦‍♂️🤦‍♂️ Funny how my brain just completely _breaks_ over a single dropped letter sometimes… 😂

**Comment by Kiarokh** [comment]
😅 funny how I didn't notice that a letter was missing, until I read your last message  🤦‍♂️🤦‍♂️🤦‍♂️

**Comment by Kiarokh** [comment]
I was even thinking, the issue title is so clear. Why does he need more info 😄
