### ISSUE TITLE
limel-dialog: scrim clicks pass through scrim and interacts with page behind scrim

### ISSUE THREAD

**Issue by adrianschmidt** [Lundalogik/lime-elements#1987]
Note that this was found in v35.0.0-next.7, confirm in newer version before trying to fix! 😅

## Current behavior

1. Use limel-dialog with `closingActions={{ escapeKey: true, scrimClick: false }}`.
2. Open the dialog.
3. Click a button on the page behind the scrim.

- The button receives the click.

## Expected behavior

The click should be caught and stopped by the scrim.

(Other interactions like hover should preferably also be prevented in the page behind the scrim.)

## Environment

- **lime-elements** version: v35.0.0-next.7
- Framework used: 
- Logs:

**Comment by Kiarokh** [comment]
I couldn’t reproduce this problem. 

Neither in Elements, 

https://user-images.githubusercontent.com/35954987/231423390-45592f5d-0df4-47a2-bbcc-514c94732256.mov



Nor in the client
https://user-images.githubusercontent.com/35954987/231423113-7c78b0f1-8f8d-45e5-84b9-ac6e508b7bb6.mov

**Comment by Kiarokh** [comment]
Let me know if that is not what you meant by "receiving clicks". Nothing seems to be interactive behind the scrim
