### ISSUE TITLE
The scroll indicator shadow in limel-dialog can be obscured by elements inside the scrolling area

### ISSUE THREAD

**Issue by adrianschmidt** [Lundalogik/lime-elements#1998]
## Current behavior

The scroll indicator shadow in limel-dialog can be obscured by elements inside the scrolling area.

https://user-images.githubusercontent.com/154725/208860351-f7d68996-1730-4e3f-b0f3-97bb5c10331c.mov

<img width="820" alt="A screenshot of the 'Custom size' example in the docs for limel-dialog, where an input field has been added to show that it is rendered above the scroll indicator shadow." src="https://user-images.githubusercontent.com/154725/208864723-566ced4c-b954-4b0f-bc0f-529a0f9e71a4.png">

1. Open the dialog in the _Custom size_ example in [the limel-dialog docs](https://lundalogik.github.io/lime-elements/versions/NEXT-36.2.0-next.4/#/component/limel-dialog/).
2. Inspect the content, and edit one of the paragraphs to add a `<input type"text">` to it.
3. Scroll the content so that the input intersects with either the top or the bottom scroll indicator shadow.

## Expected behavior

The shadow should be rendered on top of any element inside the scrolling area. Note that the shadow should not interact with clicks in any way, so we should probably set `pointer-events: none;` on it.

Note: The scrolling indicator shadow is a bit of a special hack using the css `background` property ([implemented here](https://github.com/Lundalogik/lime-elements/blob/v36.2.0-next.4/src/components/dialog/dialog.scss#L81)). As is, it's probably not possible to "lift" the shadows on top of the content. But the shadows can probably be put in `::before` and `::after` pseudo-elements instead, and those should be possible to lift above the content.

## Environment

- **lime-elements** version: 36.2.0-next.4
- Framework used: Can be reproduced in the docs

**Comment by adrianschmidt** [comment]
Here's another example from @LucyChyzhova:

https://user-images.githubusercontent.com/50618208/215755026-08d1f2eb-502b-4650-94c3-3bb289265273.mov

**Comment by LucyChyzhova** [comment]
Another example from Addon installer https://github.com/Lundalogik/limepkg-addon-installer/issues/191

**Comment by adrianschmidt** [comment]
The current implementation is one that doesn't use pseudo-elements. I'm thinking that if we change it to use pseudo-elements, we can perhaps z-index those to go above the content of the scroll area… 🤔

**Comment by adrianschmidt** [comment]
[This](https://lea.verou.me/2012/04/background-attachment-local/) is the version we're currently using, and [this](https://kizu.dev/shadowscroll/) is the version I think might be possible to adapt to do what we need.

**Comment by adrianschmidt** [comment]
<img width="656" alt="A screenshot of the history item that says 'Lucy Chyzhova moved this to ⛔️ Blocked / Won't fix in UX Backlog 🦄✨⚡️ 4 hours ago'" src="https://user-images.githubusercontent.com/154725/219693253-def99c93-eb14-4d33-b4a7-4a5c98e855ef.png">

🤨 Was that intentional?

**Comment by Kiarokh** [comment]
The [UX Backlog board](https://github.com/orgs/Lundalogik/projects/197/views/1) is a new experimental place that @FlippAre, @eketorp, @LucyChyzhova and I are using to talk about things that we should work on and prioritize. 

Not sure what made you react @adrianschmidt 😅?  
Should we remove that _blocked_ column from it instead, and remove the issues that we won't fix from the board?

**Comment by adrianschmidt** [comment]
I thought we were going to try to fix this, which is why I was surprised to see it moved to a "won't fix" status… but maybe that means "someone else will fix it", since it's simultaneously in "todo" on the Feature board? 😄

**Comment by LucyChyzhova** [comment]
@adrianschmidt  , I'm sorry that you were confused by it. 
Yes, it's just Kia and I have a different focus right now

**Comment by adrianschmidt** [comment]
No worries! 😄

**Comment by Kiarokh** [comment]
To fix this properly, we need a solution similar to what we did for the limel-tab-bar, using things like intersection observer API.
Add-ons wanted a fix for their solution. We thought this should be done in limel-dialog for everyone instead.

**Comment by adrianschmidt** [comment]
I think [the example from the add-ons installer](https://github.com/Lundalogik/limepkg-addon-installer/issues/191) is the best example. Not because it shows the bug itself, but because it shows what kind of workarounds people might make to get around the problem 😅

<img width="892" alt="image" src="https://user-images.githubusercontent.com/1732461/214036161-c43ea890-48fb-4622-8a7c-736c6c8376b0.png">

In this case, things can show up below the table, and people tend to miss that, because of the lack of indication that it's possible to scroll, as explained [here](https://github.com/Lundalogik/limepkg-addon-installer/issues/191#issuecomment-1403182557):

> This is on purpose, because if we don't have a fixed height, you might miss the content below this table if you don't realize that you can scroll.
>
> Before we had the field warnings popping up below this table. Now we have the users and groups table below this table.

**Comment by Kiarokh** [comment]
Hey guys. I added a CSS-only solution. 
This is a preview of that. What do you think?

https://github.com/Lundalogik/lime-elements/assets/35954987/3219be23-797f-4586-bea4-cbfb01512ba7


https://github.com/Lundalogik/lime-elements/assets/35954987/04793d79-46f8-408f-8fc6-009d39f3bf55

**Comment by FlippAre** [comment]
Looks great!

**Comment by adrianschmidt** [comment]
Posting here too, since Tomas and Filip might want to chime in:

> This version has its own problems:
>
> https://github.com/Lundalogik/lime-elements/assets/154725/b3f8198a-5b4d-44e4-a866-ed1e243fccc8
>
> (If the fade happens to align with an empty line, or any other whitespace large enough, it becomes completely invisible, and there is again no indication that the content is scollable.)
>
> But if we think this version is less problematic than the old one, I'm happy to merge it 👍

**Comment by FlippAre** [comment]
@adrianschmidt Good catch! 

@Kiarokh a slight gray tint to the fade might solve this? Or a fade size that is always a bit bigger than a empty line?

I think this version is still less problematic than what we we have in production today, as it will often work, and sometimes be equally as problematic but not worse ;)

**Comment by adrianschmidt** [comment]
> @Kiarokh a slight gray tint to the fade might solve this? Or a fade size that is always a bit bigger than a empty line?

Grey tint wouldn't work for this solution, since this solution doesn't ever remove the fade, it simply relies on the fade being hidden against the background when scrolled to the end. So the fade would always be visible, and therefore not mean anything 😞

> I think this version is still less problematic than what we we have in production today, as it will often work, and sometimes be equally as problematic but not worse ;)

Yeah, I agree 👍

**Comment by Kiarokh** [comment]
Yes this solution uses a CSS gradient mask basically. It gradually (using the gradient) masks the content below, until the content completely fades ut to whatever the background color of the masked element is. So we can't add edges or colors to the mask.

What we could do is adding pseudo elements of `:before` and `:after` to each edge of the container of the scrollable area. Those pseudo elements then could contain a shadow that covers the content. The bahaviour should then be like this (for a vertical scrolling):

1. Content doesn't overflow out of the container, then don't show any pseudo elements
2. Content overflows at the bottom, then only show pseudo element at the bottom.
3. if content overflows on both sides (user has scrolled), then show pseudo elements on both sides.
4. when user reaches to the bottom, show only the top pseudo element.

We do something similar in the `tab-bar`. Anyhow, this requires using intersection observers and what not, and I can't make a reusable js solution that we can simply import in each component when we need it. So I think we can go forward with what we have here, and maybe one day when i can get some help from a developer, we can write that script and implement it.

Let's merge this one
