### ISSUE TITLE
button group: reduce font size to `0,8125rem` (`13px`)

### ISSUE THREAD

**Issue by Kiarokh** [Lundalogik/lime-elements#2002]
before
<img width="504" alt="image" src="https://user-images.githubusercontent.com/35954987/209969417-1b8061ae-4103-4a16-8544-63ea64030de8.png">

after
<img width="506" alt="image" src="https://user-images.githubusercontent.com/35954987/209969505-142e9f06-0dba-4cfb-be0f-7ba97cb1b1d4.png">

**Comment by adrianschmidt** [comment]
Seconded! KBK! (Or, rather, is there anything stopping you from just doing this?)

**Comment by Kiarokh** [comment]
I was just in the middle of something
Didn't want to interrupt my flow. This is a note to remember ;)
