### ISSUE TITLE
date-picker: week picker looks different the first time it's opened

### ISSUE THREAD

**Issue by adrianschmidt** [Lundalogik/lime-elements#2024]
## Current behavior

First time the week picker is opened:
<img width="710" alt="image" src="https://user-images.githubusercontent.com/154725/211851590-493d7cc6-2be0-46b1-9b75-19469d5d23c4.png">

Second time:
<img width="710" alt="image" src="https://user-images.githubusercontent.com/154725/211851769-60dc7b3f-c6ca-4e92-a62a-0f7ccbc19605.png">

1. Just try the week picker example in the docs.

## Expected behavior

Not sure what it should look like, but it ought to be the same each time you open it…

## Environment

- **lime-elements** version: v36.2.0-next.9
- Framework used: can be reproduced in docs
- Logs:

**Comment by Kiarokh** [comment]
I also had a look at the symptoms. It seems the fist time the portal is opened, all days within the currently selected week has 3 class names of `selected`, `week` and `inRange` on them. 
<img width="1512" alt="Screenshot 2023-04-12 at 12 06 24" src="https://user-images.githubusercontent.com/35954987/231426237-72d56e2b-f144-4b9c-8a52-efeadcc35933.png">

When you hover one a week, all days within that week get the class `inRange`, which renders them as semi-transparent circles.

Next time you open it, or as soon as you pick a new day, the class names of `week` and `inRange` will disappear from all days. So it renders showing only the selected day itself.

I can't judge whether your suggestion @LawrenceBorst is bad fix or not. But I can at least confirm that this is not a CSS issue. It's a redraw issue (applying correct classes to all days of the week).

**Comment by LawrenceBorst** [comment]
Actually hold on :), we can just remove the call to `redraw` entirely and it works(!) @Kiarokh

I'm not sure why we're calling `redraw` in the first place... I thought it might have been some hack but it's part of the commit that creates more than half the flatpickr.

It seems the code works fine without the `redraw` method. It's in `componentDidUpdate`, and `this.picker` only really uses `this.inputElement, this.container, this.value`; the first two are static and the last one gets redrawn anyhow.

It's possible we could just remove the `redraw` stuff and call it a day.

**Comment by Kiarokh** [comment]
Sounds like you have a PR ready for review then? 😄 
(I will be the wrong person to review though, but feel free to make the PR). This was one of the bugs in the bugs tab.
