### ISSUE TITLE
Example description in docs for limel-grid get the wrong content

### ISSUE THREAD

**Issue by adrianschmidt** [Lundalogik/lime-elements#2026]
Instead of displaying the intended content, it displays the description for the first example on the last docs page you where on! 😮

https://user-images.githubusercontent.com/154725/212034152-ffbc4e1e-bb49-4411-af9b-4666a9456d84.mov

I suspect it might have something to do with the slot or the `@slot` doc tag… maybe? 🤨

<img width="636" alt="image" src="https://user-images.githubusercontent.com/154725/212033818-02cdfb30-32f5-4a00-8b8f-3f779fbc6bf5.png">

**Comment by Kiarokh** [comment]
I feel we should really deprecate and hide this component all together, just like what we did with `limel-flex-container`.
Controlling a CSS grid has so many features and props, and it should be handled with CSS instead.
