### ISSUE TITLE
Docs: highlight brand colors in dark mode correctly

### ISSUE THREAD

**Issue by Kiarokh** [Lundalogik/lime-elements#2034]
in the _Color system_  design guideline document. The highlighting of the brand colours determines which swatches to highlight based only on the system setting for dark mode, and doesn't account for the user's setting:

https://user-images.githubusercontent.com/154725/210375826-12396b8e-d0bd-4064-8b4f-4dcd32c3e2d2.mov

**Comment by adrianschmidt** [comment]
This one is outdated since the brand colours changed. Closing.
