### ISSUE TITLE
Dock: shadow effect of hovered buttons gets cut off

### ISSUE THREAD

**Issue by Kiarokh** [Lundalogik/lime-elements#2042]
## Current behavior

<img width="138" alt="image" src="https://user-images.githubusercontent.com/35954987/212692169-77793940-d4f8-46ce-8904-1541fe2b0134.png">

## Expected behavior
- either on hover, we need a `z-index`
- or a transparent background color for buttons by default, for non hovered buttons ⬅️  my choice

**Comment by paulinewahle** [comment]
Changed the padding-bottom
