### ISSUE TITLE
Header: simplify the basic example

### ISSUE THREAD

**Issue by LucyChyzhova** [Lundalogik/lime-elements#2043]
## Current behavior
<img width="841" alt="Screenshot 2023-01-16 at 14 44 51" src="https://user-images.githubusercontent.com/50618208/212692810-d88a46c5-be82-4dce-b003-52c71b8d6f26.png">

1. …

## Environment

- **lime-elements** version: 
- Framework used: 
- Logs:

**Comment by adrianschmidt** [comment]
That header doesn't use the default colours. It's an example with a bunch of special colours set. So this is a documentation issue, not a bug.

**Comment by adrianschmidt** [comment]
By the way, I also don't like that the first example has a bunch of weird colours. The first example should be as simple and representative as possible. That's why we usually put a "Basic Example" first.
