### ISSUE TITLE
dialog: not getting the shadow effect if an inserted component has a background color (like table)

### ISSUE THREAD

**Issue by LucyChyzhova** [Lundalogik/lime-elements#2090]
## Current behavior

https://user-images.githubusercontent.com/50618208/215755026-08d1f2eb-502b-4650-94c3-3bb289265273.mov

1. …

## Environment

- **lime-elements** version: 
- Framework used: 
- Logs:

**Comment by adrianschmidt** [comment]
This is a duplicate of #1998

**Comment by adrianschmidt** [comment]
@LucyChyzhova Feel free to put #1998 on the Feature board instead, if you want to 🙂
