### ISSUE TITLE
Select: `Changing Available Options` example needs fix

### ISSUE THREAD

**Issue by LucyChyzhova** [Lundalogik/lime-elements#2093]
## Current behavior

https://user-images.githubusercontent.com/50618208/215774893-77dd6d47-f7b2-4cec-938b-9fcf47c88f80.mov

1. …

## Environment

- **lime-elements** version: 
- Framework used: 
- Logs:

**Comment by adrianschmidt** [comment]
That's per design actually, to make sure it doesn't crash if it's given an empty set of options 😊

But we should probably clarify that in the example description… 👍

**Comment by LucyChyzhova** [comment]
aha! I see, yeah, I agree, then the description would help here 😀.
I will add it.

**Comment by adrianschmidt** [comment]
@LucyChyzhova, you said you were going to add a description here, but I don't think you ever got around to it. Should we add it, or should I just close this issue? 😊
