### ISSUE TITLE
Icon button: add `--icon-fill-color` 

### ISSUE THREAD

**Issue by Kiarokh** [Lundalogik/lime-elements#2136]
## New feature motivation
People used to use a hack and add `color:` on an icon-button, to change the fill color of the icons. 
![image](https://user-images.githubusercontent.com/35954987/219369592-314463a1-5dfd-4c5b-a14b-7049f9cc5e10.png)

![image](https://user-images.githubusercontent.com/35954987/219369550-69ff72bc-a190-4706-ac6f-982b07eefb3c.png)

This doesn't work anymore due to changes in the dark mode. Since icon colors are now defaulting to `--mdc-theme-on-surface`, to be responsive to dark mode.

## New feature description
We should offer `--icon-fill-color` as a way for them to customize it.

**Comment by adrianschmidt** [comment]
Just do it! 😍

**Comment by Kiarokh** [comment]
I actually discovered that this is not our dark-mode's fault. 
It’s probably due to an upgrade we did last summer, and bumped material design’s MDC version. It seems the styles are coming from their styles. 👇 We don't have such a thing in our code.
<img width="309" alt="image" src="https://user-images.githubusercontent.com/35954987/219389462-4fcd1ba1-2004-4ce7-b7b7-68ab5e71ae07.png">

**Comment by Kiarokh** [comment]
Then I thought I'll add `--icon-fill-color` to `limel-icon` instead, because `--icon-background-color` comes from there. so something like below would be good:
```scss
:host(limel-icon) {
	color: var(--icon-fill-color, var( --mdc-theme-on-surface));
}
```
But that's such a hard change to do. Because we have to go to every component and change wherever we have specified something like this:

https://github.com/Lundalogik/lime-elements/blob/9751250e18c63a70fe5341aecf9214afec53dcb4/src/components/banner/banner.scss#L56
We will have to change it to `--icon-fill-color: var(--banner-icon-fill-color, rgb(var(--contrast-100))); `

This will make a big-ass PR again. And I'm too tired right now to think about all the possible breaking changes that it can create, and mitigate them.

@FredrikWallstrom perhaps for now it's better that you guys use `--mdc-theme-on-surface` instead in your code, and hack it this way. I'm not sure what's the best plan ahead.

**Comment by adrianschmidt** [comment]
> perhaps for now it's better that you guys use `--mdc-theme-on-surface` instead in your code, and hack it this way. I'm not sure what's the best plan ahead.

The downside of doing that, just like the downside of the original hack, is that it's likely to break without warning, since it's not something we officially support, or even _want_ to support.

**Comment by Kiarokh** [comment]
Yes, perhaps it's better to close this issue for now.
