### ISSUE TITLE
Spinner is not shown on iPad nor iPhone

### ISSUE THREAD

**Issue by FredrikWallstrom** [Lundalogik/lime-elements#2148]
## Current behavior

limel-spinner is not shown or iPad nor iPhone.

<img width="722" alt="Skärmavbild 2023-02-23 kl  17 55 55" src="https://user-images.githubusercontent.com/21986391/220976171-8cb49cef-a5a7-4fdc-9fbd-5e9f6188755d.png">

![Skärmavbild 2023-02-23 kl  17 53 06](https://user-images.githubusercontent.com/21986391/220975544-0e4aaffb-1740-41e9-b082-b6c7721c4de9.png)

1. Render spinner on an iPhone or an iPad

## Expected behavior

Spinner should be shown.

## Env

Latest docs

**Comment by adrianschmidt** [comment]
If you untick "Lime branded (default design)" in the example in the docs, does the spinner work then?

@Kiarokh cc on this.

**Comment by Kiarokh** [comment]
seems like it's generally not shown :/ maybe a power-saver features ? 🤔

**Comment by adrianschmidt** [comment]
It seems more likely to me that we're using something Mobile Safari doesn't support, but I could absolutely be wrong 😅
