### ISSUE TITLE
input type `textarea`: the `placeholder` text does not show up

### ISSUE THREAD

**Issue by Kiarokh** [Lundalogik/lime-elements#2161]
## Current behavior

All input types show the placeholder text, except the `<limel-input-field type="textarea"` />`

## Expected behavior
☝️ they should work: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea#attributes

## Environment

- **lime-elements** version: 
- Framework used: 
- Logs:

**Comment by Kiarokh** [comment]
@LucyChyzhova do you think you can work on this one? @john-traas would need this here: https://github.com/Lundalogik/lime-crm-building-blocks/pull/42/files#r1124478915

I'll be on leadership courses, so I won't be able to contribute.

**Comment by adrianschmidt** [comment]
(Man, don't link to w3schools, you'll help their google ranking 😣 😄)

**Comment by adrianschmidt** [comment]
<img width="800" alt="A screenshot of MDN's description of the placeholder attribute: 'A hint to the user of what can be entered in the control. Carriage returns or line-feeds within the placeholder text must be treated as line breaks when rendering the hint. Note: Placeholders should only be used to show an example of the type of data that should be entered into a form; they are not a substitute for a proper label element tied to the input. See input labels for a full explanation.'" src="https://user-images.githubusercontent.com/154725/223061220-45747bb4-ff01-46af-b00e-319f07004f9f.png">
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea#attributes

**Comment by Kiarokh** [comment]
> (Man, don't link to w3schools, you'll help their google ranking 😣 😄)

it was already the first thing coming up 😅

**Comment by vicgeralds** [comment]
> it was already the first thing coming up 😅

(yes, it's been like that for ages, and people that know better complained about it for ages, because others use is as a reference)


![Image](https://user-images.githubusercontent.com/5563232/223361453-aab6c65b-c0c2-4549-9edd-33b754b4d2bb.png)
