### ISSUE TITLE
limel-Checkbox: click-event not available

### ISSUE THREAD

**Issue by olssoncharlie** [Lundalogik/lime-elements#2175]
## Current behavior

Checkboxes doesn't return event

1. Add a limel-checkbox
2. Do a log of it's onClick
3. No event is returned

## Expected behavior
Event should always be returned. Since the onclick doesn't return event, it always bubbles, making it quite hard to use in many circumstances. 

## Environment
Lime Go 
- **lime-elements** version: 34.0
- Framework used: React

**Comment by olssoncharlie** [comment]
Feels like I might have reported this before, but couldn't find it :)

Our use-case:
You should be able to bulk-update multiple meeting cards by selecting the checkboxes. The meeting cards are expandable cards. Right now the event bubbles and closes/opens the card. 
![image](https://user-images.githubusercontent.com/25174519/225333247-670a4b86-2a16-4365-b92f-24c9f15072ab.png)

**Comment by adrianschmidt** [comment]
> Event should always be returned. Since the onclick doesn't return event, it always bubbles, making it quite hard to use in many circumstances.

I'm not sure I follow… There is no `onClick` function in limel-checkbox, if that's what you mean should be returning the event?

I _think_ what you need to do is to catch the `click` event yourself, and run `.stopPropagation()` on it, but it's a little hard to know for sure without seeing a code example.

**Comment by olssoncharlie** [comment]
> I'm not sure I follow… There is no `onClick` function in limel-checkbox, if that's what you mean should be returning the event?

Ah nvm then. I assumed it accepted an onClick event, my bad for not reading the docs. I'll have to look in to our wrapper more. Thanks for the quick response :)

**Comment by adrianschmidt** [comment]
No worries! Happy I could help 🙂
