### ISSUE TITLE
Actionbar disappears when scrolling window in Edge

### ISSUE THREAD

**Issue by dorisenthecat** [Lundalogik/lime-elements#2368]
## Current behavior

https://github.com/Lundalogik/lime-elements/assets/1199682/60f411fc-63ef-4796-875b-623961813952

1. Go to documentation page for limel-action-bar using chrome
2. Scroll the window

## Expected behavior

The action bar shouldn't compress itself.

## Environment

- **lime-elements** version: NEXT-36.4.0-next.8

**Comment by LucyChyzhova** [comment]
Could not reproduce it (lime-elements/versions/37.46.1)

https://github.com/user-attachments/assets/5f5197eb-ccc3-41f5-8f97-376826496c5e
