### ISSUE TITLE
Hierarchy picker / Nested menu component

### ISSUE THREAD

**Issue by blombergedvin** [Lundalogik/lime-elements#2455]
## New feature motivation

Component is needed when setting and searching in hierarchies.

## New feature description
Some bullets of things to consider
- Hierarchy needs to be searchable
- One should be able to stop in in the middle of a hierarchy
- Keyboard navigation is important
- Clear overview of each step in the hierarchy, preferably with custom colors and/or icon on each chip/element
- One should be able to remove a object in the hierarchy
- Relations/objects should be clickable 
- Lazy loading

**Comment by Kiarokh** [comment]
closing in favor of https://github.com/Lundalogik/crm-feature/issues/1513
