### ISSUE TITLE
Autofill in dark mode

### ISSUE THREAD

**Issue by dorisenthecat** [Lundalogik/lime-elements#2460]
## Current behavior

Here are some screenshots when using the browser's auto fill function on limeel-input.

![image](https://github.com/Lundalogik/lime-elements/assets/1199682/d11a0c05-18ab-4fc1-a781-5e77ae5d1bb6)
![image](https://github.com/Lundalogik/lime-elements/assets/1199682/8e9f2949-4ad7-43ee-99f2-d072743b15d4)

In light mode it is possible to read the label but in dark mode it blends in with autofill background color. It also looks wonky when the highlighted autofilled area is so much smaller than the limeel-input box.

## Environment

- **lime-elements** version: NEXT-37.1.0-next.16

**Comment by LucyChyzhova** [comment]
Looks correct now
lime-elements/versions/37.46.1

<img width="747" alt="Screenshot 2024-07-18 at 11 05 25" src="https://github.com/user-attachments/assets/187971f9-c963-4289-aed8-9220ffc80951">
