### ISSUE TITLE
Table: Not possible to activate last row

### ISSUE THREAD

**Issue by FredrikWallstrom** [Lundalogik/lime-elements#2504]
## Current behavior

It is not possible to activate the last row in the table when the table have both the layout: `stretchLastColumn` and the class: `has-interactive-rows`.

https://github.com/Lundalogik/lime-elements/assets/21986391/285617e9-6899-42d6-8efb-76a59d6381f2

1. render a table with both stretchLastColumn layout and has-interactive-rows class
2. try to activate the last row in the table

## Expected behavior

Last row in the table should behave as all other rows when you activate and deactivate it, `activate` event should be triggered.

## Environment

![Skärmavbild 2023-09-26 kl  14 03 48](https://github.com/Lundalogik/lime-elements/assets/21986391/2f7763b2-dd38-4cc8-b575-db09b6d58e5a)

Also reproducible in lime-elements docs: https://lundalogik.github.io/lime-elements/versions/NEXT-37.1.0-next.28/#/

**Comment by LucyChyzhova** [comment]
works now

https://github.com/user-attachments/assets/38f87473-6c19-43ed-a5f4-c3b8bb08b28f
