### ISSUE TITLE
Limel-dialog: "twitching" if content grows. 

### ISSUE THREAD

**Issue by olssoncharlie** [Lundalogik/lime-elements#2634]
## Current behavior

This occurs when dialog is in taking the full screen height and an element changes. 
For example our button that slightly moves on hover creates this "twitching" effect. 

A workaround for this is to wrap the children being rendered in a `<div>` with a small margin.

![msedge_uhY3MDZLsk](https://github.com/Lundalogik/lime-elements/assets/25174519/27221973-506a-4af0-a582-6346ca208067)

1. Create a dialog that fills the full screen height
2. Have something render under certain circumstances (changes the height) 
3. Twitching begins. 

## Expected behavior

Probably shouldn't happen.

## Environment

- **lime-elements** version: 37.0.0
- Framework used: React / Stencil wrapper.

**Comment by olssoncharlie** [comment]
NVM. This was caused due to an element overflowing on X-axis. 
Twitching is still new from upgrading though, so not sure if it's something you want to investigate, I'll close for now :) @adrianschmidt

**Comment by adrianschmidt** [comment]
😲

That's fugly… 😞

Was it the slider that was overflowing, or something else?

**Comment by olssoncharlie** [comment]
> 😲
> 
> That's fugly… 😞
> 
> Was it the slider that was overflowing, or something else?

I think it was a combination:
The slider has a collapsable section that is visible when slider is 0, this created the (very small) vertical scrollbar. 
Our pipeline picker (dropdown above the statuspicker) had a negative margin for positioning. This caused the horizontal scrollbar. 
 
At least I think this was the case. Doesn't really make sense why that would create this behavior, but removing it fixed the issue. 
 
We did a couple of major bumps 34->37, so it started occuring sometime there.
