### ISSUE TITLE
limel-menu searcher returns wrong result when there are no search hits

### ISSUE THREAD

**Issue by BjornOstberg** [Lundalogik/lime-elements#2660]
## Current behavior

When you are sending an empty search result into limel-menu. It will "show all" instead of an empty result.

https://github.com/Lundalogik/lime-elements/assets/1814702/d6582c40-9619-47c9-bd86-31f38fce3578

## Expected behavior

When no search hits, it should show no hits or the given `emptyResultMessage`

## Environment

https://lundalogik.github.io/lime-elements/versions/NEXT-37.1.0-next.75/#/component/limel-menu/

**Comment by blombergedvin** [comment]
@Kiarokh or @LucyChyzhova or @adrianschmidt, where do you want us to put this issue? Some specific board?

**Comment by Kiarokh** [comment]
added it to our cooldown, so we can talk about it. 
if you guys fix this, please add a PR and we can put it in review there. this makes it much easier.

**Comment by civing** [comment]
We think this should be either very easy to fix or very "strange". Could you guys give a stab at fixing this @TommyLindh2 ?

**Comment by TommyLindh2** [comment]
Yeah sure, we can take a look in the beginning of next year, before the cycle starts.
