### ISSUE TITLE
limel-picker - multiple: remove one value clears all when value is object

### ISSUE THREAD

**Issue by BregenzerK** [Lundalogik/lime-elements#2758]
## Current behavior

When you use `limel-picker` with `multiple` and an object as value and you remove one value, all values are removed.
![image](https://github.com/Lundalogik/lime-elements/assets/10260886/f54dab87-b43a-4a4e-84a3-077e2f337ba1)
 

1. `limel-picker` like this:
```
<limel-picker
                label={"Test"}
                multiple={true}
                searcher={this.search}
                onChange={this.handleChange}
                value={this.recipientsValue}
            />


private handleChange = (
        event: LimelPickerCustomEvent<Array<ListItem<RecipientValue>>>
    ) => {
        this.recipientsValue = event.detail;
}

export interface RecipientValue {
    id: number;
    limetype: string;
    address: string;
    name: string;
}
```
2. pick several values
3. remove one of them --> all values are cleared, as shown in the screenshot, the picker emits an empty array

## Expected behavior

Only remove the value that was clicked on. It works fine, when value on `ListItem` is a simple value e.g. a number instead. 

## Environment

- **lime-elements** version: "37.1.0-next.97"

- Framework used: StencilJs

**Comment by Kiarokh** [comment]
@BregenzerK are you sure this is not dependent on your implementation? I'm testing it other places, but it seems to be working fine. 🤔

**Comment by BregenzerK** [comment]
> No I was just testing with existing examples and implementations of the picker, such as in Lime Elements. I don't think I'm the right person for this task to be honest. It'd be way more effective if you or your team makes a PR i elements I'd say.

It doesn't have to be you and it isn't super urgent. Sure we can look at it, but so can anyone in the feature team I guess

**Comment by LucyChyzhova** [comment]
UPD: Katja and I created an example that contains an object as a value and we could reproduce the problem  in `lime-elements`.  I will continue with an investigation.

https://github.com/Lundalogik/lime-elements/assets/50618208/7569adcb-2c14-475b-92ba-643b54685a9a

**Comment by Kiarokh** [comment]
please send me the example code @LucyChyzhova and we will test it in this PR: https://github.com/Lundalogik/lime-elements/pull/2777

**Comment by adrianschmidt** [comment]
One thing that struck me while helping Lucy a little with this, is that `limel-picker`'s `value` property was typed as `ListItem<number | string> | Array<ListItem<number | string>>`, so it seems to me like you ought to have gotten a compiler error when you tried to pass in a `ListItem<T>` where `T` was some kind of object… 🤔

https://github.com/Lundalogik/lime-elements/pull/2784/files#diff-4a10e2cfaa535f50e4e86a2dcc0614e52c64ba1e38c8f287c9dde9c8d04bb6d9L112

Do you know where it's being used with an object @BregenzerK? I'd love to have a look.

Although, we have had some trouble with the types not being exported properly from lime-elements, so perhaps that's why there was no error 🤷‍♂

**Comment by BregenzerK** [comment]
> One thing that struck me while helping Lucy a little with this, is that `limel-picker`'s `value` property was typed as `ListItem<number | string> | Array<ListItem<number | string>>`, so it seems to me like you ought to have gotten a compiler error when you tried to pass in a `ListItem<T>` where `T` was some kind of object… 🤔
> 
> https://github.com/Lundalogik/lime-elements/pull/2784/files#diff-4a10e2cfaa535f50e4e86a2dcc0614e52c64ba1e38c8f287c9dde9c8d04bb6d9L112
> 
> Do you know where it's being used with an object @BregenzerK? I'd love to have a look.
> 
> Although, we have had some trouble with the types not being exported properly from lime-elements, so perhaps that's why there was no error 🤷‍♂

It's been weird a bit with the ListItem interface, it enforced the interface in general but not at all the interface for the value.  you can see it in action on [this PR](https://github.com/Lundalogik/limepkg-email/pull/410/files). I had hoped that adding `RecipientValue` to all the `ListItem` definition would give me autocompletion and potential building errors, but it didn't.

**Comment by adrianschmidt** [comment]
> It's been weird a bit with the ListItem interface, it enforced the interface in general but not at all the interface for the value. you can see it in action on [this PR](https://github.com/Lundalogik/limepkg-email/pull/410/files). I had hoped that adding `RecipientValue` to all the `ListItem` definition would give me autocompletion and potential building errors, but it didn't.

I think it's because of the issues we've had with exporting the typings. I pulled down that PR branch, rebased it on main, and tried building it. No errors. But when I installed the latest lime-elements, the build failed with a bunch of errors about incompatible types.

**Comment by adrianschmidt** [comment]
Although… hmm… the _latest_ lime-elements should be OK with the types you are using, I would have thought… since we merged a fix for this issue… 🤔
