### ISSUE TITLE
Not possible to click on document chip to open file

### ISSUE THREAD

**Issue by FredrikWallstrom** [Lundalogik/lime-elements#2793]
## Current behavior

Not possible to click on document chip to open file, nothing happens.

1. Click on a document chip on a document object

## Expected behavior

File should be opened/downloaded

## Environment

- **lime-elements** version: 37.4.0
- Framework used: StencilJS
- Logs: Nothing

**Comment by adrianschmidt** [comment]
I've found the problem, and I'm working on finding a solution 😊

**Comment by Befkadu1** [comment]
> I've found the problem, and I'm working on finding a solution 😊

I told you, you are awesome 😄
