### ISSUE TITLE
It is not possible to change color of limel-collapsible-section

### ISSUE THREAD

**Issue by LarsCJensen** [Lundalogik/lime-elements#284]
## Current behavior

It is set to white as default

## Expected behavior

It should be able to be set through own css.

## Environment

Senaste versionen.

**Comment by adrianschmidt** [comment]
This was actually fixed in [v26.4.0](https://github.com/Lundalogik/lime-elements/releases/tag/v26.4.0) (PR #581). I had forgotten this issue existed, otherwise I would have tagged that PR to close this 🙂

Ping @LarsCJensen
