### ISSUE TITLE
text editor: Code and Code block don't have titles

### ISSUE THREAD

**Issue by Kiarokh** [Lundalogik/lime-elements#3049]
<img width="348" alt="image" src="https://github.com/Lundalogik/lime-elements/assets/35954987/80947606-7329-476c-9a4d-ed3ba3a74337">

**Comment by Kiarokh** [comment]
@john-traas do you know why their titles won't show up?

**Comment by john-traas** [comment]
We most likely haven't added translations for them. I will link a quick PR to this issue.
