### ISSUE TITLE
limel-picker: add placeholder

### ISSUE THREAD

**Issue by BregenzerK** [Lundalogik/lime-elements#308]
connect to Lundalogik/crm-feature#772

## New feature motivation
A placeholder would help in order to be more direct about, what the user is suppose to be doing. 

## New feature description
add property `placeholder` and display it in the input field
![image](https://user-images.githubusercontent.com/10260886/53001515-17db5900-342b-11e9-8be6-46a35ccf8ead.png)

**Comment by adrianschmidt** [comment]
This was fixed in #393 which closed #363
