### ISSUE TITLE
limel-dialog: indicate scrollable content via a shadow

### ISSUE THREAD

**Issue by BregenzerK** [Lundalogik/lime-elements#312]
## New feature motivation

Because there aren't any visible scroll bars on iOS, it's pretty hard to recognise scrollable content in the dialog right now

## New feature description

add a shadow on the bottom of the dialog, that indicates invisible content

## New feature implementation

this might help: https://stijndewitt.com/2018/06/12/pure-css-drop-shadow-on-scroll/

**Comment by adrianschmidt** [comment]
See discussion on PR: #412
