### ISSUE TITLE
iOS: native tabbing doesn't work

### ISSUE THREAD

**Issue by BregenzerK** [Lundalogik/lime-elements#313]
## Current behavior
- open the lime-element documention on an iOS device and go to e.g. the input-field.
- focus the first input 
- press the down arrow to jump to the next input field
  
## Expected behavior
it should blur the first input and set focus on the second.

## Environment

- **lime-elements** version: 16.0.1

**Comment by adrianschmidt** [comment]
This seems to be working now (see video below), so I'm closing this. If there are still problems somewhere, please comment with where.

https://github.com/Lundalogik/lime-elements/assets/154725/44be42d0-706c-4a3a-bfcd-781031d4b07f
