### ISSUE TITLE
limel-markdown: component crashes if supplied value contains malformed html

### ISSUE THREAD

**Issue by adrianschmidt** [Lundalogik/lime-elements#3149]
Reported in [Open Hours in Teams](https://teams.microsoft.com/l/message/19:8eb8d446f40d4696ba03bee0d3b47a56@thread.tacv2/1709122481382?tenantId=15f5bb21-07a4-42c6-ada2-08965bd62081&groupId=2f699c45-fe12-4487-81ae-829eb08a675a&parentMessageId=1709122481382&teamName=Lime%20CRM&channelName=Dev%20Open%20Hours%20(Tues%20and%20Thurs%2010.00%20-%2011.00)&createdTime=1709122481382), and [in the forum](https://forum.lime-crm.com/t/communcation-comes-as-code-and-wont-send-replys-suddenly/6100).

## Current behavior

If the supplied string contains an html tag with a blank line (2 consecutive line breaks) between the opening (`<`) and closing (`>`) brackets, the component crashes while parsing, and no output is displayed at all.

1. Supply the following input to a limel-markdown instance, for example via the composite example in the docs:
	```
	<p>this paragraph is correct</p>
	<p
	
	>this paragraph is broken</p>
	<p>here is another correct paragraph</p>
	```

- Nothing is rendered.

## Expected behavior

While this isn't really wellformed html, browsers and email clients _do_ handle this, and therefore we kind of _have_ to in order for the component to be useful in Lime CRM. The output should ideally be rendered as if there was no line breaks inside the tag, but it should at least not crash completely and not output _anything_.

## Environment

- **lime-elements** version: confirmed in [v37.57.5](https://github.com/Lundalogik/lime-elements/releases/tag/v37.57.5), but likely present in all previous versions that has the `limel-markdown` component.
- Framework used: Can be reproduced in the docs.
- Logs:

**Comment by TommyLindh2** [comment]
@adrianschmidt I think this is related, we have still reports about "faulty" rendering in communication flow since we started using `limel-markdown`.


Here's an example that will render incorrectly:

It will render the `</style></span>` as text, do you think it's possible to fix?

```
<div><span><style>

</style></span>

Hello2

</div>
```

**Comment by adrianschmidt** [comment]
Great! As long as there are no downsides where we eat unreasonable amounts of performance, or have to make trade-offs where we need to break some other cases to make something work, it's lovely if we can make the component more forgiving 🙂

If there are trade-offs to be made, then it might be better to let the consumer make those trade-offs by pre-processing the value before sending it in to limel-markdown.

**Comment by TommyLindh2** [comment]
> Great! As long as there are no downsides where we eat unreasonable amounts of performance, or have to make trade-offs where we need to break some other cases to make something work, it's lovely if we can make the component more forgiving 🙂
> 
> If there are trade-offs to be made, then it might be better to let the consumer make those trade-offs by pre-processing the value before sending it in to limel-markdown.

Is this something you will take a look at during this cooldown or would you like us to look over alternatives on our side?

**Comment by adrianschmidt** [comment]
> Is this something you will take a look at during this cooldown or would you like us to look over alternatives on our side?

"Cooldown" is always the most stressful time for me, so I can't promise I'll have time this cooldown. I'd very much appreciate it if you would like to look into improvements that can be made in the `limel-markdown` component, and I'd certainly do my best to review any PRs! ❤️

**Comment by TommyLindh2** [comment]
I don't really know what we are expected to contribute with, and what implications the "John fix" would potentially cause.
So is one solution to just create a PR based on Johns code and try it out in the docs, see that the default examples behaves the same and that it fixes our issue? That way we can have a discussion regarding that change.

I'll created a new issue because it's no the same issue as this: https://github.com/Lundalogik/lime-elements/issues/3209
