### ISSUE TITLE
limel-menu: opening the menu scrolls the page to the top

### ISSUE THREAD

**Issue by adrianschmidt** [Lundalogik/lime-elements#3166]
## Current behavior

1. Scroll the page down, and find a menu to open.
2. Click the menu

- the page scrolls to the top

We seem to also lose focus from the element, rather than move focus from the menu trigger to the first element in the menu. I'm not sure if this is related. Possibly the lost focus could even be the cause of the scrolling.

I have not been able to reproduce the bug in the Lime CRM Web Client. That might simply be because we never scroll the whole page in the web client, only different elements.

## Expected behavior

No scrolling should happen

## Environment

- **lime-elements** version: 37.59.1
- Framework used: Can be reproduced in the docs
- Logs:

**Comment by Kiarokh** [comment]
can't reproduce
