### ISSUE TITLE
chip: when `loading` add `aria-busy="true"`

### ISSUE THREAD

**Issue by Kiarokh** [Lundalogik/lime-elements#3170]
The Chip component has a loading state. 

So when it is loading, we need to add `aria-busy="true"`.

Read more https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-busy

**Comment by adrianschmidt** [comment]
@paulinewahle When there's an issue that a PR fixes, we usually put the issue on the board (and move it to review when that time comes), rather then just the PR. Just an FYI 🙂

(I've removed the PR from the board and added the issue instead.)
