### ISSUE TITLE
popover: no `backdrop-filter` in Chromium

### ISSUE THREAD

**Issue by Kiarokh** [Lundalogik/lime-elements#3238]
### Reported to Chrome 👇 

The `backdrop-filter` style doesn't work in Chromium anymore, due to `animation` on parent element. Doesn't happen in Firefox and Safari.

On [this page](https://lundalogik.github.io/lime-elements/versions/37.63.0/#/component/limel-popover/), there is a popover element (see attached screenshot). It has a div: `<div class="limel-popover-surface">` with `backdrop-filter`. However, since its parent element `limel-popover-surface` has an animation that changes `opacity` and `transform` styles, the `backdrop-filter` does not work anymore. Unchecking the animation or any of these styles will render the backdrop filter correctly again.

<img width="243" alt="Screenshot 2024-10-10 at 15 29 48" src="https://github.com/user-attachments/assets/38434892-9731-44c2-a2da-e8cd8ea1b5b3">

**Comment by adrianschmidt** [comment]
While a bit clunky, it ought to be possible to create a workaround by removing the problematic styles when the animation has finished. For example, target a class which is only applied during the time the animation runs, and then removed again.
