### ISSUE TITLE
text editor: use `⌘` + `shift` + `option` + `c` to activate Code Block

### ISSUE THREAD

**Issue by Kiarokh** [Lundalogik/lime-elements#3281]
<img width="442" alt="image" src="https://github.com/user-attachments/assets/44b3f51d-b77a-4e45-8936-27a8d04a3810">

Currently we are using `⌘` + `shift` + `c`, but that is a default browser hotkey, used to inspect elements. This makes it sometimes annoying to inspect the webclient, as the focus is in the text editor, and it activates the Code Block instead.

Also, using `⌘` + `shift` + `option` + `c` seems to be the convention.

**Comment by john-traas** [comment]
The issue with this suggestion is that the 'Alt' or option key can change the value of a character. Using the option (alt) key on my laptop turns the C character into Ç.

**Comment by Kiarokh** [comment]
I think we can close this issue. Perhaps not so important after all
