### ISSUE TITLE
Input: the email icon uses a hardcoded RGB, coming from MDC

### ISSUE THREAD

**Issue by Kiarokh** [Lundalogik/lime-elements#3319]
<img width="430" alt="image" src="https://github.com/user-attachments/assets/743a5895-a4dc-4874-8fb9-62274e3e5a9f">

<img width="313" alt="image" src="https://github.com/user-attachments/assets/b17403a4-8c03-4cfa-847b-a8391e2b434c">

<img width="1037" alt="image" src="https://github.com/user-attachments/assets/3969d1f4-77c5-4418-91b3-9c0f2392aa0f">

**Comment by abhishekpawar1060** [comment]
I want to work on this issues #3319

**Comment by NourHany** [comment]
hello, i fixed the issue and when i'm opening a PR i get permission denied. how can i fix this?

**Comment by NourHany** [comment]
Opened a PR for this issue: https://github.com/Lundalogik/lime-elements/pull/3322
