### ISSUE TITLE
Minor improvements to limel-picker (badge size, positioning, help text)

### ISSUE THREAD

**Issue by magnusfagerlund** [Lundalogik/lime-elements#363]
1. Decrease the size of the icon (see image)
2. Add help text "Search and connect to [limetype]" (see images)
3. Lower the suggestions menu so that you see the line underneath (see image)
4. Always show 5 suggestions if there are (never show scrollbar)
![limelpicker](https://user-images.githubusercontent.com/7524499/57289061-f6e5e400-70ba-11e9-8404-f2cee8504362.png)

**Comment by adrianschmidt** [comment]
#393 fixes 1) and 3), and adds options for 2) and 4). To actually fix 2) and 4), some additional changes are needed in lime-webclient.
