### ISSUE TITLE
Possibility to autofocus limel-input-field

### ISSUE THREAD

**Issue by joelricci** [Lundalogik/lime-elements#409]
## New feature motivation

It would be really neato if you, for instance, have a dialog with an input field and have the input field to autofocus when you open the dialog.

## New feature description

A new `autofocus` property on `limel-input-field` would do the trick. 

## New feature implementation

I tried
```
10 PRINT "AUTOFOCUS"
20 GOTO 10
```
but it didn't work.

**Comment by Kiarokh** [comment]
This seems to be solve already. Because we're doing it on column filter popovers. I close it
