### ISSUE TITLE
Date & time properties are not formatted nicely in limel-picker

### ISSUE THREAD

**Issue by magnusfagerlund** [Lundalogik/lime-elements#461]

**Comment by magnusfagerlund** [comment]
![Inkeddatetime bug in limelpicker_LI](https://user-images.githubusercontent.com/7524499/66288362-379b9080-e8d9-11e9-80f3-7fca0040f2ed.jpg)

**Comment by adrianschmidt** [comment]
Thinking out loud:

This might or might not be something we can and/or should fix in Lime Elements.

If we're getting a Date object from the consumer, it would be quite nice to detect that, and automatically format it in some way more reasonable than this.

The problem then is to what precision we should format it. Reasonably, the consumer would want to control that, but I'm not sure if we really want the consumer to supply some kind of formatting config. It seems much easier to just let the consumer supply a formatted string to begin with.

These are just my spontaneous thoughts of things we should consider before making a complex solution in Lime Elements.
