### ISSUE TITLE
Add a line between objects in list in limel-picker

### ISSUE THREAD

**Issue by adrianschmidt** [Lundalogik/lime-elements#465]
Similar to how the object-picker in lime-webclient looks.

See the "Visuals, dividers, and spacing" section of the Material Design specification: https://material.io/components/lists/#anatomy

**Comment by adrianschmidt** [comment]
I've been experimenting with the lines and the icon badge sizes.

The size explicitly specified by the Material specification for the case we're looking at is the one we call `medium`, which is the one we used before making the badges smaller. It's 40x40 px.

The badge size used by limel-picker right now is `x-small`, which I think we all agree is too small.

In-between we have `small`, images of which you can find below the images of the `medium` sized badges. I actually think `small` looks the best, but I think there is a great deal to be said for keeping to the specification and simply using `medium`.

I've also tried adding a divider-line, as per the Material specification. The specification allows for adding a divider line between items, when one is needed to distinguish items from each other, primarily in cases where the list items are three lines vertically, but there are a few examples of using dividers with two-line items as well.

All examples with badges (called "avatars" in the Material spec) use the "inset" version of the divider, which is also what I've used below. One disadvantage of using lines between each list-item is that dividing list-items into groups becomes difficult, since the obvious choice—a line—has already been used for a different purpose. By using the inset line, it *might* still be possible to use a line reaching from edge to edge to signify a group.

Honestly though, I definitely prefer the list without divider-lines between each item. It might look unfamiliar after using our old list, but I think it's a better design, and familiarity comes with use.

Medium icons, no lines:
<img width="998" alt="Screenshot 2019-10-09 at 11 40 35" src="https://user-images.githubusercontent.com/154725/66470595-2f368780-ea8a-11e9-9e58-d046d6b220ee.png">

Medium icons, with lines:
<img width="998" alt="Screenshot 2019-10-09 at 11 39 17" src="https://user-images.githubusercontent.com/154725/66470640-47a6a200-ea8a-11e9-8000-d647c2aa71aa.png">

Small icons, no lines:
<img width="998" alt="Screenshot 2019-10-09 at 11 41 40" src="https://user-images.githubusercontent.com/154725/66470669-5725eb00-ea8a-11e9-872b-460583a0ba51.png">

Small icons, with lines:
<img width="998" alt="Screenshot 2019-10-09 at 11 38 20" src="https://user-images.githubusercontent.com/154725/66470695-6442da00-ea8a-11e9-9795-b1e7f3929b4b.png">

@magnusfagerlund

**Comment by adrianschmidt** [comment]
Oh, and another comment about the divider-lines:

Currently, I've simply let the limel-list render the line for any lists that are two-line and have badge-icons.

While it's possible to make that configurable, so that limel-picker can tell limel-list to render those lines, while they aren't rendered by default, I really think we should avoid that, in favour of consistent look and feel between components.

![image](https://user-images.githubusercontent.com/154725/66475072-e1724d00-ea92-11e9-9046-b3afa61529ef.png)

**Comment by adrianschmidt** [comment]
> I say we go for `small `and having a divider line. I still believe it makes it easier for users to distinguish between objects.

Ok, let's go with that.

Should we use the `small` size for lists in general? Or should other lists still default to the `medium` size?

**Comment by magnusfagerlund** [comment]
> Should we use the small size for lists in general? Or should other lists still default to the medium size?

I think we should use `small ` to be consistent.

**Comment by adrianschmidt** [comment]
Hmm… found yet another consideration:

Either we default lists with icons that are *not* on badges to `small` as well (which is the easier option), but then those icons really become quite small:

![image](https://user-images.githubusercontent.com/154725/66547684-083a8d00-eb40-11e9-8a84-44fe3669fcde.png)

Or we jump through some minor hoops to have the icons default to `medium` when not on badges, which looks much better on its own, but doesn't align with lists that have icon badges of default size:

![image](https://user-images.githubusercontent.com/154725/66547773-43d55700-eb40-11e9-892e-045873ac5cf2.png)

I guess we probably won't have those two kinds of lists shown above and below each other all that often, but it won't look great when they are.

**Comment by adrianschmidt** [comment]
Hmm… now that I look closer at those screenshots, the lists doesn't actually line up perfectly when the same size is set either… that's odd… they really should 🤔
