### ISSUE TITLE
limel-slider: updating value on slider after sliding it doesn't update the marker pin

### ISSUE THREAD

**Issue by wric** [Lundalogik/lime-elements#469]
## Current behavior

If I drag the slider with the mouse pointer to a value and then modifies the value from, for example, a button, the marker will still show the first value I set with the mouse.

![bild](https://user-images.githubusercontent.com/942721/66575583-700bca80-eb76-11e9-856d-3286be3ab782.png)

![slider](https://user-images.githubusercontent.com/942721/66576260-af86e680-eb77-11e9-97ee-39020b2890f0.gif)

## Expected behavior

The marker should reflect the current value no matter if it is set with the mouse or pragmatically. 

## Environment

- **lime-elements** version: 22.6.1
- Framework used: StencilJS
- Logs: N/A

## Thoughts

The marker is implemented as:

```tsx
<div class="mdc-slider__pin">
    <span class="mdc-slider__pin-value-marker">
        {this.multiplyByFactor(this.value)}
    </span>
</div>
```
I think the MDC component sets the `innerText` of the `span` on release of mouse button (over-writing our value). We could do the same in `watchValue()` but I'm not sure if that's the best solution.

**Comment by adrianschmidt** [comment]
Good catch! Thanks for reporting!
