### ISSUE TITLE
limel-picker - property 'required' does not work as expected

### ISSUE THREAD

**Issue by erikmangsten** [Lundalogik/lime-elements#470]
## Current behavior

The picker do not show that this is required a field (other elements use a * to show that it is required) and when you select a item with a limel-picker the text is still red:

![image](https://user-images.githubusercontent.com/19487039/66648738-92f8b600-ec2c-11e9-97e8-0ed9374dfad3.png)

## Expected behavior

The Picker should highlight that this is a required field and when a value is selected it should turn green

## Environment

- **lime-elements** version: 22.6.1
- Framework used: stenciljs

**Comment by adrianschmidt** [comment]
This was fixed in v24.1.0 👍
