### ISSUE TITLE
limel-input-field: when type is number, clicking on the arrows in Chrome updates the input twice

### ISSUE THREAD

**Issue by adrianschmidt** [Lundalogik/lime-elements#475]
## Current behavior

1. Use a field of type `number`. The one in the docs for input-field works.
2. Click the arrows for increasing and decreasing the value.

- The value increases or decreases by 2 for each click.

Discovered it in Chrome on macOS. Haven't tried in other browsers yet. Could possibly be a browser bug?

## Expected behavior

The value should increase or decrease by 1 for each click.

## Environment

- **lime-elements** version: 24.5.0
- Framework used: Can be reproduced in the docz-app.
- Logs:

**Comment by magnusfagerlund** [comment]
Cannot reproduce. Fixed in newer browser version?

**Comment by adrianschmidt** [comment]
> Cannot reproduce. Fixed in newer browser version?

Yeah, I can't reproduce either 👍
