### ISSUE TITLE
Number component: Setting min/max property

### ISSUE THREAD

**Issue by magnusfagerlund** [Lundalogik/lime-elements#499]
## Current behavior

In LISA, you can set min/max value for integer fields. These properties are not in use in the web client when creating new objects.

![min max property](https://user-images.githubusercontent.com/7524499/67901586-6f5bc800-fb67-11e9-9799-c2cf9a7e828a.png)

## Expected behavior

Min/max property should be used. For a field configured according to the example above, it should not be possible to set a value lower than 0.

**Comment by jgroth** [comment]
Support for min/max validation was added in 4afe197 (part of #557)
