### ISSUE TITLE
Portal for limel-menu

### ISSUE THREAD

**Issue by FredrikWallstrom** [Lundalogik/lime-elements#529]
## Current behavior

I was trying out the new start page grid for the activity matrix and found out one frustrating thing. Every element in the matrix is a limel-menu, and when I open one menu it will be hided when it comes outside the given grid space for the matrix, because the grid is set to overflow hidden. The picture below is self-explaining.

![Skärmavbild 2019-12-04 kl  13 41 04](https://user-images.githubusercontent.com/21986391/70155182-145f4880-16b2-11ea-854e-18ab361f8c48.png)

## Expected behavior

It would be nice if the behavior is the same as it is for the limel-select (see picture below). So a portal could be a solution, don't know if there is other possible solutions. 
I was trying to solve it with a portal but did not manage to succeed. It was a little bit tricky, so I think it is better experienced people take care of it instead of me wasting time on it :) Then I could have a look on the solution instead and learn from it!

![Skärmavbild 2019-12-04 kl  16 22 24](https://user-images.githubusercontent.com/21986391/70155284-4375ba00-16b2-11ea-9b9e-324c0e7f349b.png)

## Environment

- **lime-elements** version: 25.0.0

- Framework used: lime-dev-app
- Logs:

**Comment by adrianschmidt** [comment]
I think we might remove the `overflow:hidden` styling on the grid-components.

Removing it does increase the risk that one misbehaving component could affect other components, but I think it's worth taking that risk to avoid this type of issues.

**Comment by Kiarokh** [comment]
I believe it's a good idea. It's simpler that the top-level governing framework focuses on providing guidelines and trusts that components will behave correctly. If they don't, someone will complain and they must simply correct themselves. :)
