### ISSUE TITLE
limel-select: distinguish disabled option more  

### ISSUE THREAD

**Issue by BregenzerK** [Lundalogik/lime-elements#538]
## Current behavior

besides the mouse pointer you can't see a difference between enabled options (first and third) and the disabled one
![image](https://user-images.githubusercontent.com/10260886/71165860-dfc2c380-2251-11ea-8b16-9473eec424d5.png)

## Expected behavior

different background color and/ or font-color for the disabled option 
bug got introduced when we updated @limetech/material-components-web

## Environment

- **lime-elements** version: 26.0.1

**Comment by jgroth** [comment]
Root cause is probably in the list, seems the same issue is in there. Only the checkbox is grey for disabled items
![Screenshot from 2019-12-19 12-17-31](https://user-images.githubusercontent.com/1088928/71169585-9aa28f80-2259-11ea-8d9c-fa3869d73e16.png)
