### ISSUE TITLE
limel-dialog doesn't respect --dialog-height

### ISSUE THREAD

**Issue by joelricci** [Lundalogik/lime-elements#590]
## Current behavior

Dialog adapts height to content. 

## Expected behavior

Height of the dialog should respect `--dialog-height`

## Environment

- **lime-elements** version: 24.6.2
- Framework used: Stencil 1.8.5
- Logs: n/a

**Comment by adrianschmidt** [comment]
@magnusfagerlund Ping for prioritisation 🙂

**Comment by justFredster** [comment]
@magnusfagerlund this is the reason behind the behavior that you reported as weird in ACD. So, it is super important then right? ;)

**Comment by magnusfagerlund** [comment]
Not critical, but would of course be very helpful. Someone in the add-ons team that could look at it during cooldown?
