### ISSUE TITLE
Text area component/element

### ISSUE THREAD

**Issue by TommyLindh2** [Lundalogik/lime-elements#605]
## New feature motivation
There is very common that customers have multi line text fields in their desktop solution.
This is basically one step closer of getting rid of the desktop client.

## New feature description
I think it speaks for itself, basically support for a text area component.

## New feature implementation
I have made a custom component for the SMS component I've built.
I've started from your implementation of the the input field and tried doing a similiar implementation, but as an text area instead.

You can see that implementation here: [SMS component implementation](https://github.com/Lundalogik/addon-manual-sms/tree/go-to-python/frontend/src/components/lwc-addon-manual-sms-text-area)

**Comment by jensgustafsson** [comment]
Merged and released a few days ago!

https://github.com/Lundalogik/lime-elements/commit/701e1b3f857b062c06debed828db6b4b464d6d0a  🎉

**Comment by TommyLindh2** [comment]
Super NICE!

**Comment by jensgustafsson** [comment]
Anyway, awesome initiative! If you had created the  PR just a few days earlier it might very well been your PR that was merged.
