### ISSUE TITLE
Too small margin over limel-slider

### ISSUE THREAD

**Issue by sofiehelgesson** [Lundalogik/lime-elements#626]
## Current behavior

I have a slider under an input field and the name of the slider is placed over the previus field, see picture

![image](https://user-images.githubusercontent.com/24894627/75969670-93416880-5ecf-11ea-8ce4-325d5377551b.png)

## Expected behavior
More margin

## Environment
- **lime-elements** version: 22.3.0

**Comment by adrianschmidt** [comment]
This is a confirmed bug. The height of the host-element is not enough to include the floating label. We need to either increase the height, move the label down, or a combination of both.

@Kiarokh probably has an opinion?

**Comment by Kiarokh** [comment]
@adrianschmidt I think the nicest solution could be that we move down the 0% and 100% labels together with the [green current % indicator]. Then slider's main label ("Probability" in this case), would have space and can be placed where 0% is now in this picture. This way, we are following Material Designs placement-convention of labels. 

However, the downside of this approach is that the green indicator that shows the chosen percent will be covered by users' fingertips on touchscreen devices when it's being dragged :( So they temporarily won't see the chosen procent, which will make it hard to guess (I assume smarter users will move down their finger while dragging the slider though, so they can see the indicator). The mouse cursor may also cover the indicator partially. On the other hand, if we leave the indicator on top, it will cover the slider's label (when it is on lower procents close to zero). Meanwhile, we want to avoid having so much horizontal dead-space (which means solving the problem only by increasing the height of the component). 

So given all these potential problems, what I can think of right now is to move the indicator up on top of the slider track, while the drag handle is being dragged. As soon as user releases the drag handle, the green indicator can jump down again. I think this is the optimal solution, but I have no clue how hard it is to do it this way.

**Comment by adrianschmidt** [comment]
> So given all these potential problems, what I can think of right now is to move the indicator up on top of the slider track, while the drag handle is being dragged. As soon as user releases the drag handle, the green indicator can jump down again. I think this is the optimal solution, but I have no clue how hard it is to do it this way.

Haha, having read halfway through your second paragraph, this was exactly my thought as well 👌

It's probably either (near)impossible or very easy. I'm guessing the MDC component applies a css class while dragging occurs, in which case moving the indicator should be very straightforward. If it doesn't apply a class, it will probably be a lot trickier, if even possible at all.

**Comment by Kiarokh** [comment]
😄 that's cool. I know you think like a designer too 👌
Another simpler solution can be moving the %indicator to the top left and place it beside the slider's label. So it won't move. (This is in case we can't get the auto-applied class)
