### ISSUE TITLE
limel-list looks broken when some items have two lines and some only one

### ISSUE THREAD

**Issue by adrianschmidt** [Lundalogik/lime-elements#663]
## Current behavior

![image](https://user-images.githubusercontent.com/154725/77421382-043bb800-6dcc-11ea-83ea-17e98e39f361.png)

## Expected behavior

The items with only one line of text should have the text centered, similar to when there are no multi-line items in the list:
![image](https://user-images.githubusercontent.com/154725/77421344-f5ed9c00-6dcb-11ea-95f5-6bc3eb926490.png)

## Environment

- **lime-elements** version: 26.11.3
- Framework used: AngularJS (lime-webclient, old object card details)
- Logs:

**Comment by Kiarokh** [comment]
we had fixed this @jensgustafsson right? The issue seems to be old. I'll close this.

**Comment by adrianschmidt** [comment]
> we had fixed this @jensgustafsson right? The issue seems to be old. I'll close this.

![image](https://user-images.githubusercontent.com/154725/85849717-c6c03f80-b7ab-11ea-96a5-7c1f04db1d8b.png)

Seems to be fixed, yes 👍
