### ISSUE TITLE
Missing "upper label" for input field of type textarea

### ISSUE THREAD

**Issue by FredrikWallstrom** [Lundalogik/lime-elements#722]
## Current behavior
Input Field of Type Textarea
When we prefill the input field with some text the "upper label", or whatever it is called, is not visible.

![Skärmavbild 2020-04-22 kl  14 34 04](https://user-images.githubusercontent.com/21986391/79983542-35c9a100-84a8-11ea-9703-1fcf0a529a09.png)

When we focus the input field, the upper label appears.

![Skärmavbild 2020-04-22 kl  16 18 43](https://user-images.githubusercontent.com/21986391/79993343-f190cd80-84b4-11ea-8ef5-8bce7c78c3fb.png)

## Expected behavior

The upper label should be visible from the beginning without focus the input field.

## Environment

- **lime-elements** version: v26.18.0
- lime-dev-app

**Comment by adrianschmidt** [comment]
This seems to have mostly been fixed already. There's just a small bug left where the last letter of the label "Message" gets cut off when the textarea is focused while empty. If you enter some text, then blur the textarea, the last "e" appears, and it stays when you focus the textarea again. I'll double check with some longer and shorter labels as well, to see what happens.

**Comment by adrianschmidt** [comment]
Update: The missing part of the label grows bigger the longer the label is. I'd be very surprised if we are doing anything directly to set this value, but we could still be creating the bug, if, for example, we have changed the font-size of the label when floating. It might also flat out be a bug in MDC. The problem isn't there in MDC's demo of the component, but the demo probably uses v6.x, while we're still using v4. (Yes we should upgrade, we just need to take the time to actually do it… 😅)

**Comment by adrianschmidt** [comment]
![lime elements textarea floating label](https://user-images.githubusercontent.com/154725/82447607-cea00c00-9aa8-11ea-9ce7-596f0e6abb93.gif)

**Comment by FredrikWallstrom** [comment]
> This seems to have mostly been fixed already. There's just a small bug left where the last letter of the label "Message" gets cut off when the textarea is focused while empty. If you enter some text, then blur the textarea, the last "e" appears, and it stays when you focus the textarea again. I'll double check with some longer and shorter labels as well, to see what happens.

Hmm, strange I'm running lime-elements version 26.24.0 and I still have issues with missing label. If that is supposed to be fixed we probably do something wrong in our code.

![Skärmavbild 2020-05-20 kl  14 51 34](https://user-images.githubusercontent.com/21986391/82448215-b5e42600-9aa9-11ea-8708-ace81e872a1f.png)
![Skärmavbild 2020-05-20 kl  14 52 46](https://user-images.githubusercontent.com/21986391/82448223-b7ade980-9aa9-11ea-9fd7-6dab458c2510.png)

**Comment by adrianschmidt** [comment]
The latest published docs are for v26.13.0 (because our automatic publishing doesn't work as it should and has been disabled), and there I see exactly the same behaviour as in the gif i posted.

But, I assume the text visible in you screenshot is actually the label? So the problem there doesn't seem to be that the label is missing, but that there's a notch in the border even though the label isn't floating yet?

**Comment by FredrikWallstrom** [comment]
![Skärmavbild 2020-05-20 kl  15 37 36](https://user-images.githubusercontent.com/21986391/82452643-d6af7a00-9aaf-11ea-8d7f-6bd2a49d9dbd.png)

No, the text that is visible is not the label.
The problem is that we are putting some initial text to the `value` property, like this

```
@State()
private value: string;

componentWillLoad:
   value = "LIME Administrator wants you to sign GDPR + Lime CRM."

render:
   lime-input-field:
      value = this.value
```

When we do that, the label don't appear until we focus the text field.

Hope you get it :)

**Comment by adrianschmidt** [comment]
Sorry about not replying sooner.

Yes, I understand. Now I see that you say "when we prefill" in the original report. I don't know why I missed that.
