### ISSUE TITLE
tab content are too close to edges

### ISSUE THREAD

**Issue by Kiarokh** [Lundalogik/lime-elements#745]
the `<div class="limel-list-container">` in `crm-components` (or other view mode containers that come in future) needs some adequate padding on the sides. Otherwise the content will stretch to the edges and in a small screens (e.g. Phone or Related view), the interface will look very cramped.

### Note
I think the `<div class="tab-content">` in `lime-elements` cannot and should not have this padding. The reason is that the padding is related to the content (view modes [map, list, table, etc..]). Some view modes may not need the paddings (e.g. the map).

Or should we in those cases add a negative `margin` to them instead? What do you think @adrianschmidt

**Comment by magnusfagerlund** [comment]
Please add some more context to this issue

**Comment by adrianschmidt** [comment]
> the `<div class="limel-list-container">` in `crm-components` (or other view mode containers that come in future) needs some adequate padding on the sides. Otherwise the content will stretch to the edges and in a small screens (e.g. Phone or Related view), the interface will look very cramped.
> 
> ### Note
> I think the `<div class="tab-content">` in `lime-elements` cannot and should not have this padding. The reason is that the padding is related to the content (view modes [map, list, table, etc..]). Some view modes may not need the paddings (e.g. the map).
> 
> Or should we in those cases add a negative `margin` to them instead? What do you think @adrianschmidt

Exactly, it's the parent element's responsibility to add any necessary whitespace around components. If a component adds whitespace outside itself, that will cause all kinds of trouble.

So, this isn't an issue that belongs in lime-elements. Please create one in lime-crm-components or crm-feature instead.
