### ISSUE TITLE
New line in Limel-button

### ISSUE THREAD

**Issue by internationalWOT** [Lundalogik/lime-elements#750]
## Current behavior

When writing longer sentences/tags in limel-button components and a new line is added. the CSS does not seem to handle the new line and the text in the button seems to be outside of the button itself.

## Expected behavior

The expected behaviour would be that the text is located properly within the borders of the button.
![bugg limbutton](https://user-images.githubusercontent.com/25244272/81157997-d67b8e80-8f87-11ea-92fa-053744b6cc2a.PNG)

**Comment by adrianschmidt** [comment]
Wow, that's a long label for a button… 😯

We should of course handle that as gracefully as possible, but I'm not sure that's ever going to look _good_… 😞

It might help you in more cases than this if the Limetype could be called something just a tad shorter.

**Comment by Kiarokh** [comment]
I also suspect if this is a problem of the buttons. It's most probably a problem within the design of your project at a larger scale, or choice of label. An action label should be short and concise. 

If the function of this button is not clear from it's containing context, and cannot be further clarified, maybe you could use `limel-tooltip` to further explain what the button actually does. ⚠️ limel-tooltip is currently a `private` component, so use it at your own risk in case we update something in future without announcing it as a breaking change.

**Comment by Kiarokh** [comment]
closing… read above : ☝️
