### ISSUE TITLE
Switch to popperjs breaks Lime Admin 2

### ISSUE THREAD

**Issue by sampsonbryce** [Lundalogik/lime-elements#774]
## Current behavior

Pull the latest lime-webclient and upgrade lime admins lime-elements dependency from 26.20.0 to 26.21.0. After the upgrade if you open up lime admin 2, all the dropdown popovers are hidden, meaning if you click on a select element the dropdown menu is not shown.

I have a screencast of the issue: https://lime-technologies.slack.com/files/ULTJS18Q2/F013YB1KAQ5/lime-admin-hidden-select-popover.mp4

## Expected behavior

Dropdown popups should show

## Environment

- **lime-elements** version: 26.21.0. The issue does not appear in 26.20.1. I believe it is related to the switch to popperjs for the popup container
- Framework used: Angular
- Logs: N/A

## Initial debugging

When comparing the popup css on version 26.20.1 vs 26.21.0 it seems that popperjs uses different css rules that cause issues with z-indices. Specifically the transform rule that is applied to the popup causes it to loose its z positioning and therefor be hidden behind the mat-sidebar elements since they have z-indices of 1 or 3.

**Comment by adrianschmidt** [comment]
@magnusfagerlund: Ping. This looks important…

@jgroth: Did you reproduce the error, or just label and add the PR to the project (which imo is perfectly fine, if that's the case)?

**Comment by magnusfagerlund** [comment]
Yes, this needs prioritization

**Comment by jgroth** [comment]
I have not tried to reproduce it :slightly_smiling_face: 
I just labeled it and put it on the board :smile:
