### ISSUE TITLE
limel-select label spans out of the element in condensed width

### ISSUE THREAD

**Issue by terryilebode6** [Lundalogik/lime-elements#780]
the label of the picker goes out of the element in a situation where the width of the element is less than the width of the label 
<img width="884" alt="Screen Shot 2020-05-25 at 15 51 24" src="https://user-images.githubusercontent.com/60092998/82819294-70a46780-9ea0-11ea-8ba1-c95cc5f644d9.png">

<img width="932" alt="Screen Shot 2020-05-25 at 15 51 07" src="https://user-images.githubusercontent.com/60092998/82819286-6f733a80-9ea0-11ea-909f-94eacf3deb82.png">

**Comment by Kiarokh** [comment]
@terryilebode6 ready 4 u! :)
