### ISSUE TITLE
fix icon trailing alignment in fields

### ISSUE THREAD

**Issue by Kiarokh** [Lundalogik/lime-elements#783]
![image](https://user-images.githubusercontent.com/35954987/82899651-a0647580-9f5b-11ea-86c6-6434f0e7e28f.png)
The ( i ) icon goes to the top-right edge. It has to be like this:

![image](https://user-images.githubusercontent.com/35954987/83027114-04586e00-a030-11ea-927b-bb1ff566d0ab.png)

**Comment by Befkadu1** [comment]
> mdc-text-field--with-trailing-icon

I will look at it. It needs a small fix
