### ISSUE TITLE
limel-dialog height exceeds screen height

### ISSUE THREAD

**Issue by joelricci** [Lundalogik/lime-elements#786]
## Current behavior

When dialog content exceeds screen or viewport height and no `--dialog-height` constraint is set, the height of the dialog will stretch beyond screen/viewport boundaries. 

![image](https://user-images.githubusercontent.com/1732461/82920027-13c7b080-9f77-11ea-9f39-f672d34c2ed5.png)

See related issue for details: https://github.com/Lundalogik/limepkg-esign/issues/232

## Expected behavior

The height of the dialog should never extend beyond screen boundaries. 

## Environment

- Tested on: iOS 13.4.1 / Safari, Chrome Desktop 81.0.4
- **lime-elements** version: 26.24.0
- Framework used: `lime-webclient: 46.23.0`, `@limetech/lime-web-components: 3.1.0`, `@stencil/core v1.12.7`
- Logs: n/a

**Comment by adrianschmidt** [comment]
@magnusfagerlund I've put this in the Inbox. It seems like it should be very easy to fix it though, so we should perhaps just move it to Ready for Dev?

cc @Kiarokh: in case you have any comments?

**Comment by magnusfagerlund** [comment]
I agree! It would be great to solve now!

**Comment by Kiarokh** [comment]
@adrianschmidt let's talk about it and see what are our options and how we solve it best. I think the modal layouts generally need some real love :)

**Comment by adrianschmidt** [comment]
> @adrianschmidt let's talk about it and see what are our options and how we solve it best. I think the modal layouts generally need some real love :)

I don't think we should couple fixing this bug with a bigger redesign of the component though. That will invariably delay the bugfix.

**Comment by magnusfagerlund** [comment]
I agree with Adrian. A redesign should be a completely other issue.
