### ISSUE TITLE
input-field not respecting invalid prop

### ISSUE THREAD

**Issue by sampsonbryce** [Lundalogik/lime-elements#791]
## Current behavior

The mdcTextField will not respect the invalid class put onto the containing label component and will instead reset the classes based on its own calculation of whether or not the component is valid, likely based on native input attributes such as required and the type.

### Steps to reproduce
* Pull master
* Get lime-elements into the browser somehow
* Insert `<limel-text-field invalid help-text="help text" value=""></limel-input-field>` into the dom
* The text field should be red signifying that it is invalid (since the invalid prop is set). 
* Click to focus the input field
* Click away to blur the input field
* Note that the red styling due to the invalid state is missing due to loss of focus. This is incorrect the red styling should remain since the invalid prop is set

## Expected behavior

If I set the invalid prop to true the field should be shown as invalid regardless of the internal validation of the text field.

## Environment

- **lime-elements** version: 26.27.0
- Framework used: N/A the issue shows when using lime-elements in an empty html page.
- Logs: N/A

## Proposed Solutions
https://github.com/Lundalogik/lime-elements/pull/788

**Comment by adrianschmidt** [comment]
@sofiehelgesson I think this might have been the problem you experienced the other day?
