### ISSUE TITLE
Make a new chips UI, which only is used to illustrate "Filters".

### ISSUE THREAD

**Issue by Kiarokh** [Lundalogik/lime-elements#804]
## Why do we need a new chip style?

The challenge is that we need to have a component for filters which is visually distinct and easily recognizable. The component should be informative, and users must quickly and easily recognize it, wherever they see it. They must directly know that this is not a "chip" or a "button", this is a "filter"!

## The challenge
​For instance, have a look at the "[Chips component](https://material.io/components/chips#usage)" in Material Design, which is used for may proposes, from tags, to contact avatars, weird buttons, and even filters.​ This is simply super confusing.
​
Or have a look at this limited set of shapes that is offered in almost all UI-design libraries today. Which one is suitable/available/good to play the vital role of filters in our product? How would these work on mobile devices, specially when there are many filters together?​
![image](https://user-images.githubusercontent.com/35954987/84147039-03c2cd00-aa5d-11ea-98c6-7dbab7af23f0.png)

Filters should be visually distinct and easily recognizable from the rest of the UI elements, so that users can dare to click them with peace of mind and expect a consistent result. We must invent something new!​ What shape can we use?

# Proposed design
The component looks like a chip, but one of the corners is not as rounded as the rest.
![image](https://user-images.githubusercontent.com/35954987/84147207-4b495900-aa5d-11ea-888a-b45c4e180da4.png)
![image](https://user-images.githubusercontent.com/35954987/84147247-5c926580-aa5d-11ea-85e9-74c29418dd18.png)
![image](https://user-images.githubusercontent.com/35954987/84147474-c14dc000-aa5d-11ea-9c04-fdd4b5d364ff.png)
![image](https://user-images.githubusercontent.com/35954987/84147505-ce6aaf00-aa5d-11ea-8c83-c6386f3d9aed.png)

**Comment by Kiarokh** [comment]
More design discussions and studies here: https://lundalogikab.sharepoint.com/:p:/s/uxcrm/EeOoPTgC50tCker9LPecm7oBvn7AssPVa5z4VqsDiYpwgw?e=OxGktZ

**Comment by adrianschmidt** [comment]
I think this was fixed in #2707, right? @Kiarokh

**Comment by Kiarokh** [comment]
yapp
