### ISSUE TITLE
Build process compiles unnecessary CSS.

### ISSUE THREAD

**Issue by Kiarokh** [Lundalogik/lime-elements#814]
## Current behavior
the build process compiles unnecessary CSS. For example it adds `px` in front of all `0` values. So if you write `padding: 0 0 0 1rem;` you will get: `padding: 0px 0px 0px 1rem;`. Or if you write `border: 1px solid black`, you will get: 
```
border-width: 2px;
border-style: solid;
border-color: black;
border-image: initial;
```
This eventually makes the generated CSS big and dirty for no reason.

## Expected behavior
Compile nice and tidy CSS.

## Environment

- **lime-elements** version: 
- Framework used: 
- Logs:

**Comment by adrianschmidt** [comment]
Will fixing this really be worth the time we'd spend on it? We're maybe talking a few milliseconds for a non-cached page-load…

**Comment by Kiarokh** [comment]
Well, it totally depends on the time it takes to fix it :) if it is just changing some compiling settings it would be nice to do it. 

In some situations, inspecting the CSS becomes a bit hard due to this. Specially because you can't easily uncheck or tweak the styles in web components; and you have to `unset` them one by one.
