### ISSUE TITLE
Watcher won't catch/output changes in imported SCSS files

### ISSUE THREAD

**Issue by Kiarokh** [Lundalogik/lime-elements#831]
## Current behavior
Let's say you have a component with partial styles, stored elsewhere (not in the main styles file for that component). 
Example in the table component:
`@import './partial-styles/tabulator-arrow';`
If you change styles in this file, you must rerun the `npm start` command to rebuild the whole thing, while changes in the main scss file are always compiled in real-time.

## Expected behavior
Watcher should detect those changes and include them in the compiled version.

## Environment

- **lime-elements** version: 
- Framework used: 
- Logs:

**Comment by adrianschmidt** [comment]
Did you restart the watcher after creating the file? The watcher won't pick up on files created while the watcher is running.

If this is a bug, it's a bug in Stencil, and should be reported to them. Closing this.

**Comment by Kiarokh** [comment]
Thanks @adrianschmidt . Yes the file is already there, but the watcher won't care.
