### ISSUE TITLE
Multi-selection of rows, to do bulk actions

### ISSUE THREAD

**Issue by Kiarokh** [Lundalogik/lime-elements#835]
![image](https://user-images.githubusercontent.com/35954987/97295535-b4383e80-184f-11eb-9c50-5151201f8387.png) using this strange button should be considered forbidden, unlawful, and vicious. 😄

- This is a very unconventional way of such actions. 
- Very hard to discover or guess the functionality related to the button. 
- It's not clear that EVERYTHING (which may not even be seen in the current page/view) is gonna be affected.

## Correct interaction design
![image](https://user-images.githubusercontent.com/35954987/85680777-e6336b80-b6ca-11ea-8d5b-6ceea1d9d9ec.png)

Possibilities of doing bulk actions / mass operations should be presented only when rows are selected (check boxes beside them are checked). Therefore:
- We need to have a specific place to click on (it can be the first cell that looks like a check box), to be able to select a row for bulk actions, because clicking on the entire row will open up related view.
- As soon as the first row is selected, we need to show a contextual menu that includes the bulk actions.
- There should be a top-most checkbox that selects all visible rows currently presented to the user
- There should be a counter in front of it, showing how many items are selected in total. The counter should of course change, if user deselects an item, after selecting all first.
- If there is active pagination (only a series of items are presented in the first page), the interface should provide the possibility to select even none-visible items (currently not on the page).

a sketch for a better solution can be like below 
![image](https://user-images.githubusercontent.com/35954987/97297632-93bdb380-1852-11eb-8ed0-44165eb4e3a3.png)

## updating footer values when items are selected
Table footer fields such as average or sum) should get updated when items are selected using checkboxes (bulk operations) and only show respective numbers for selected items (not for all).

**Comment by eketorp** [comment]
This is so much released already.
