### ISSUE TITLE
Empty limel-icons in limel-tab-bar

### ISSUE THREAD

**Issue by JohannesHansen** [Lundalogik/lime-elements#847]
## Current behavior
Tabs always render an icon element even if no icon name is defined, resulting in uneven whitespace.
![image](https://user-images.githubusercontent.com/3470434/86156409-33b63b00-bb06-11ea-9dcb-4979e3f9de40.png)

## Expected behavior
The tabs should only render icons when the tab has an icon name defined.

## Environment

- **lime-elements** version: 26.34.5
- Framework used: React

**Comment by adrianschmidt** [comment]
This should be really easy to fix. I'm putting in Ready for dev so someone can grab it during the summer 👍
