### ISSUE TITLE
Tab-bar crashes when previous tabs are undefined

### ISSUE THREAD

**Issue by JohannesHansen** [Lundalogik/lime-elements#852]
## Current behavior
If the second argument to `tabsChanged` is undefined, the component crashes and renders the text "undefined". This seems to happen quite frequently when using the component in a react wrapper.

## Expected behavior
Component shouldn't crash and should not render "undefined"

## Environment

- **lime-elements** version: 26.35.0
- Framework used: React

**Comment by adrianschmidt** [comment]
@jgroth I'm almost certain I've seen this as an issue on the board during the last cycle? Wasn't this fixed already? Or am I confusing it with something similar?

**Comment by jgroth** [comment]
I'm not sure I have seen it here, but there has been a similar issue in another component. It should be quite easy to fix by giving default values to the arguments, i.e.
```ts
protected tabsChanged(newTabs: Tab[] = [], oldTabs: Tab[] = [])
```

**Comment by adrianschmidt** [comment]
I'm putting this one straight on the Feature board, since it seems like a good task for someone to grab during summer.
