### ISSUE TITLE
Handling missing values in schema forms

### ISSUE THREAD

**Issue by sampsonbryce** [Lundalogik/lime-elements#859]
## Current behavior

In a schema form, if for example an input field is given a value, and the value is then removed from the input field, the input field will emit a value of `null`. `null` is a specific type in json schemas and as such unless the marshmallow schema specifies `allow_none` validation in the backend will fail.

## Expected behavior

If I delete all the text from an input element the value should be treated as non existent instead of null.

## Environment

- **lime-elements** version: 26.35.0
- Framework used:
- Logs:

## Steps to Reproduce
- Use this marshmallow schema as a plugins schema
```python
    class TestSchema(Schema):
        name = fields.String(title="Name", description="Enter a value and then remove the value")

        class Meta:
            ordered = True

```
- Navigate to where the schema is rendered in lime admin
- Save the schema (should save successfully)
  - You can inspect the network request of the save and see that the saved schema is `{}`
- Enter any text into the input field
- Remove the text from the input field
- Save the schema (should fail)
  - You can inspect the network request of the save and see that the saved schema is `{ name: null }` this is not valid as we did not specify `allow_none` in the marshmallow schema.

## PR's
#860

**Comment by adrianschmidt** [comment]
@BregenzerK @jgroth If we like this change, how about we put this in *In Progress* on our regular board? That way it's easier to keep tabs on what's going on, I think.

**Comment by BregenzerK** [comment]
I didn't see the attached PR. I thought Bryce just opened an issue and I didn't feel in any position to prioritize it. but yes, with the PR it probably should be even in the revie column ;)
