### ISSUE TITLE
limel-date-picker schema form widget does not emit string value in datetime or time format

### ISSUE THREAD

**Issue by sampsonbryce** [Lundalogik/lime-elements#862]
## Current behavior

If the schema form is datetime or time, a datetime or time input field is rendered, but when the value changes, the emitted value is always in the format of YYYY-MM-DD.

## Expected behavior

When the date-picker is of datetime or time type, it should get an appropriately formatted datetime/time string

## Environment

- **lime-elements** version: 26.35.0
- Framework used: Stencil
- Logs:

**Comment by adrianschmidt** [comment]
Hmm… if we output a string on the format `YYYY-MM-DD` for `date` and `datetime`, then that's clearly a bug. But I'm not entirely sure if we should output a differently formatted string or simply a `Date` object. I'm also not sure what we output from the regular limel-date-picker at the moment (when not used in a form that is).

The argument I would present for outputting a `Date` object would be that we tend to use full dates, whether as objects or as json, complete with timezone, and that's the way we want our add-ons to handle dates as well, as times and dates without timezones are terrible for customers spanning multiple timezones (like we do ourselves).

On the other hand, we do typically want these components to feel like drop-in replacements for native components, and looking at the native input when using the different available date related types, they use formatted strings, with no timezone.

For Lime CRM, I think the former argument, for using `Date` objects, is the stronger one. Using differently formatted strings for different pickers puts the conversion work on the add-ons, and would be like asking for inconsistent and incompatible use of dates.

Thoughts for Field @sampsonbryce and Go @JohannesHansen?

cc for thoughts, @BregenzerK @jgroth @jensgustafsson

**Comment by sampsonbryce** [comment]
@adrianschmidt This issue is specifically addressing the limel-date-picker widget that we use to connect react-jsonschema-form to lime-elements, not the actual limel-date-picker. The regular date picker I believe emits dates just fine and I believe the regular limel-date-picker emits Date objects which seems fine to me. The problem comes from this date widget which needs to emit an onChange event with a string value of the date instead of a Date object in order for it to work well with react-jsonschema-form.

**Comment by jgroth** [comment]
Having it output a `Date` object from the field inside the form would probably be ideal. However, I'm not sure if it is possible since the `type` field in the schema is `string` and there is no `date` type in JSON schema.

**Comment by adrianschmidt** [comment]
> Having it output a `Date` object from the field inside the form would probably be ideal. However, I'm not sure if it is possible since the `type` field in the schema is `string` and there is no `date` type in JSON schema.

Then I would suggest always outputting the result with `JSON.stringify(date)` where `date` is a `Date` object, regardless of the format chosen. If that would work?

**Comment by jgroth** [comment]
Yes that would probably work :slightly_smiling_face:

**Comment by sampsonbryce** [comment]
We need to make sure the output format is compatible with marshmallows Date, Time and DateTime fields though right? Since the marshmallow schema is the consumer of the data from the date-picker schema form widget?

**Comment by vicgeralds** [comment]
> Then I would suggest always outputting the result with JSON.stringify(date) where date is a Date object, regardless of the format chosen. If that would work?

No, that only works with the `date-time` format.  If we're using JSON Schema, it would be weird to just ignore its formats https://json-schema.org/understanding-json-schema/reference/string.html#dates-and-times

**Comment by vicgeralds** [comment]
This was fixed in 022ee9dc93e548df73b42a7c5fda5c63f651a342
