### ISSUE TITLE
limel-picker: drop down list is stuck after scrolling

### ISSUE THREAD

**Issue by joelricci** [Lundalogik/lime-elements#865]
## Current behavior

When the drop down list is populated and **at least one** selection has been made, after scrolling the list it seems stuck and it's not possible to focus another element outside its bounds. Only way to "exit" is making a selection in the list.

## Expected behavior

* It should always be possible to focus an element outside the drop down list (by clicking outside its bounds)

## To reproduce:
1. Make at least one (1) selection
1. Scroll the list by grabbing the scroll bar
1. Try to click the search input field or anywhere outside the list
1. Select an item in the list - now the operation is back to normal

## Environment

- **lime-elements** version: verified on >=26.29.0
- Framework used: @limetech/lime-web-components: 3.1.0, lime-webclient: 46.32.1

![picker scroll bug](https://user-images.githubusercontent.com/1732461/86613186-83d34880-bfb1-11ea-9cbd-6ff26f8c38d8.gif)
__

**Comment by adrianschmidt** [comment]
### 😮

That's not so good… I'll try reproducing when I have a minute, and if I can, I'll put this in *Ready for Dev*, so it will hopefully be fixed during summer.

**Comment by adrianschmidt** [comment]
I can only reproduce this when hovering grabbing the scrollbar "thumb" and dragging it around. And it can be dismissed by selecting a value (and if the value is unwanted, removing it again).

So unless I've missed some situation where the bug is worse than that, I'll leave it for normal triage.

**Comment by eketorp** [comment]
May be related to #1062

**Comment by adrianschmidt** [comment]
> May be related to #1062

Yes, they seem closely related. I played around with reproducing this one, and the problem appears when the picker loses focus but doesn't close the dropdown. At that point, we've probably detached the listers for closing the dropdown when clicking outside it. And for some reason we also don't react to and focus the picker when clicking inside it.
