### ISSUE TITLE
Truncate text in limel-select

### ISSUE THREAD

**Issue by FredrikWallstrom** [Lundalogik/lime-elements#892]
## Current behavior

I have a fixed width of my limel-select element and css property `overflow: hidden` activated. The selected text get hidden, which is great. However, I want the text to be truncated (that has worked before)

![Skärmavbild 2020-07-17 kl  14 39 50](https://user-images.githubusercontent.com/21986391/87787095-6157ef80-c83b-11ea-84bc-5d14a31ef47b.png)

![Skärmavbild 2020-07-17 kl  14 41 39](https://user-images.githubusercontent.com/21986391/87787267-a3813100-c83b-11ea-8e10-932d40d54997.png)

## Expected behavior

I want the text to be truncated, like this. I have solved it here by moving (or adding?)   

  overflow: hidden;
  white-space: nowrap;
  text-overflow: ellipsis;

To the `limel-select-trigger` css class. However, I have not created a PR for that because I not sure if that is a reasonable solution.

![Skärmavbild 2020-07-17 kl  14 44 11](https://user-images.githubusercontent.com/21986391/87787480-feb32380-c83b-11ea-98a2-49dabc45ed31.png)

![Skärmavbild 2020-07-17 kl  14 44 41](https://user-images.githubusercontent.com/21986391/87787522-1094c680-c83c-11ea-9826-19db6d69c1de.png)

## Environment

- **lime-elements** version: "26.40.4"
- Env: Web client

**Comment by Kiarokh** [comment]
@FredrikWallstrom this must be solve in some previous versions of lime elements. I'll close the issue, but if you still experience problems let me know. ;)
