### ISSUE TITLE
limel-select with multiple selection broken on phone

### ISSUE THREAD

**Issue by BregenzerK** [Lundalogik/lime-elements#919]
## Current behavior

it opens the native selector/ dropdown where you can't select multiple options and returns undefined when selecting one.
reported on the forum: https://forum.lime-crm.com/t/error-in-web-component-on-mobile/2814

## Environment

- **lime-elements** version: 26.27.4
- Framework used: stencil

**Comment by adrianschmidt** [comment]
The component only breaks when the `value` property of the options supplied to limel-select is not of type `string`. The native html element requires a string for this value, so while we could probably build a conversion into the limel-select component itself, the PR #972 simply improves the documentation so make it clear that the value must be a string. I think that should be good enough.
