### ISSUE TITLE
chip-set: keyboard-navigation for delete-all button broken

### ISSUE THREAD

**Issue by adrianschmidt** [Lundalogik/lime-elements#936]
## Current behavior

1. You can tab to the clear-button, but there doesn't seem to be any way to actually activate it. I've tried both \<enter\>  and \<space\>.
![image](https://user-images.githubusercontent.com/154725/91960616-6816c500-ed0a-11ea-99ac-1436b0e6e2e1.png)
2. If you don't hover the component when tabbing to the clear-button, it looks a bit broken:
![image](https://user-images.githubusercontent.com/154725/91960635-706f0000-ed0a-11ea-9be8-ca6fe2675950.png)
3. It's possible to tab to the button when there are no chips selected.
4. When disabled, it's still possible to tab to the button:
![image](https://user-images.githubusercontent.com/154725/91961655-c2645580-ed0b-11ea-9e96-2c8dd352639d.png)
5. When read-only, it's not only possible to tab to the button, but it also becomes visible when any chip is hovered:
![image](https://user-images.githubusercontent.com/154725/91962042-4cacb980-ed0c-11ea-8641-38f9f79e83be.png)

(Ignore the issue with the label cutting part of the chips, when disabled or read-only, that's an unrelated problem, and belongs in a separate issue.)

## Expected behavior

1. Pressing <enter> should activate the button.
2. The button should appear correctly when tabbed to, whether or not the component is being hovered.
3. The button should be taken out of the tab-flow when the component has no chips. We should probably use `display:none`, so it's also hidden from assistive tech.
4. Regardless of if the component is empty or has chips, it should not be possible to tab to the button when the component is disabled.
5. Same as for disabled, no tabbing to the button when the component is read-only, and also don't show the button on hover.

## Environment

- **lime-elements** version: v28.1.0 (introduced in #931)
- Framework used: reproducible in docz-app
- Logs:

**Comment by Kiarokh** [comment]
Thanks @adrianschmidt! This is great.

**Comment by Kiarokh** [comment]
@maltja these are things we achieved with changes yesterday.
Not sure about the *readonly* mode yet, we must check this as well as changing the `<i>` to `<a>` for the sake of keyboard navigation.
