### ISSUE TITLE
limel-button-group shows radio button in Firefox

### ISSUE THREAD

**Issue by wric** [Lundalogik/lime-elements#942]
## Current behavior

![bild](https://user-images.githubusercontent.com/942721/92107317-dd0afd00-ede5-11ea-9056-a059f24e3462.png)

## Expected behavior

As in Chrome ;)

![bild](https://user-images.githubusercontent.com/942721/92107359-ebf1af80-ede5-11ea-812a-da1a82233aeb.png)

## Environment

- **lime-elements** version: 28.1.1 (from the documentation page)
- **Firefox** version: 80.0.1 (64-bit)

**Comment by adrianschmidt** [comment]
I'm guessing this won't be a priority, since the Lime CRM Web Client doesn't officially support Firefox. But pull requests are welcome!

**Comment by adrianschmidt** [comment]
This seems very similar to Lundalogik/crm-feature#1353, so I'm guessing they are the same issue, and the difference is just that Firefox renders the radio-buttons differently on macOS and Windows.

So PR #943 should hopefully fix this issue 👍
