### ISSUE TITLE
limel-select shows as invalid before focusing on the field

### ISSUE THREAD

**Issue by sofiehelgesson** [Lundalogik/lime-elements#944]
## Current behavior

I have a dialog for creating project activities and I think that the behaviour of limel-select differs from the other elements.
When I first render the dialog all fields are grey even though the values in them are invalid. But after focusing on a field it will be red if the value are invalid. This is all fine. But if the user press the save button a project activity is created and the some values are emptied and the user can start filling it in again to create a secord project activity. But now the limel-select field are red from the beginning while the other ones are grey.

![image](https://user-images.githubusercontent.com/24894627/92215025-801a5000-ee94-11ea-9623-3e164257a2bf.png)

## Expected behavior

I would like it to be grey until focusing on it.

## Environment

- **lime-elements** version: 26.31.1

**Comment by magnusfagerlund** [comment]
Is this still an issue @sofiehelgesson?
