### ISSUE TITLE
limel-input-field, type="textarea" don't update "value" when @State() is updated

### ISSUE THREAD

**Issue by erikmangsten** [Lundalogik/lime-elements#952]
## Current behavior

When a component updates a `@State()` parameter that is used in a `limel-input-field` with `type="textarea"` the value is not updated. Therefor it looks like the previous text entered in the parameter

This works in a normal `limel-input-field`

## Expected behavior

The value in the component updates

## Environment

- **lime-elements** version: 26.3.0

**Comment by adrianschmidt** [comment]
Bug confirmed. Added to inbox for prioritisation.

**Comment by adrianschmidt** [comment]
It was easy enough to fix, so I've opened a PR for it 🙂

**Comment by erikmangsten** [comment]
> 
> 
> It was easy enough to fix, so I've opened a PR for it 🙂

Great! Figured out a workaround for the problem, but this will hopefully save future people time! :D
