### ISSUE TITLE
resetting the value for input field of type textarea doesn't show

### ISSUE THREAD

**Issue by sofiehelgesson** [Lundalogik/lime-elements#965]
## Current behavior

I reset the values for most of the input fields after creating a record. But for the textarea the value is not updated. The text shown in the textarea is not the current value of that variable.
![image](https://user-images.githubusercontent.com/24894627/94568424-bfa64300-026c-11eb-9753-5bd713ea22ed.png)

## Expected behavior
That the textarea reflects the value of my variable

## Environment

@limetech/lime-elements: "28.4.3"

**Comment by adrianschmidt** [comment]
This should be fixed by #954, released in [v28.5.3](https://github.com/Lundalogik/lime-elements/blob/master/CHANGELOG.md#2853-2020-09-29).
