### ISSUE TITLE
Some logic in the input chip set example could be moved to the input chip set component instead

### ISSUE THREAD

**Issue by maltja** [Lundalogik/lime-elements#966]
Some logic written in the example for the input chip set should maybe be moved to the chip set component instead. For example, should not the functions onInput and onKeyUp always work the same way for all chip sets?

```javascript
    private onInput(event: CustomEvent<string>) {
        this.textValue = event.detail;
    }

    private onKeyUp(event: KeyboardEvent) {
        if (
            (event.key === ENTER || event.keyCode === ENTER_KEY_CODE) &&
            this.textValue.trim()
        ) {
            this.value = [
                ...this.value,
                this.createChip(this.textValue.trim()),
            ];
            this.textValue = '';
        }
    }
```

**Comment by adrianschmidt** [comment]
No. The consumer might not want to create new chips from the input. For example, `limel-picker` uses `limel-chip-set`, but text input isn't used to create a new chip, it's used to search for existing objects, and once one is chosen, a chip is created to represent that object.

I'll close this for now. Please do comment if I've misunderstood something, and you think this should be reopened.
