### ISSUE TITLE
Select menu appears underneath dialog (seems to only be an issue in the docs)

### ISSUE THREAD

**Issue by adrianschmidt** [Lundalogik/lime-elements#979]
## Current behavior

Update: It seems like this isn't a problem when lime-elements is used in lime-webclient, so this might only happen in the kompendium docs.

When a limel-select is placed inside a limel-dialog, and the select menu is opened, the menu appears underneath the dialog and the dialog scrim:

![image](https://user-images.githubusercontent.com/154725/95314221-525c6880-0891-11eb-9b10-cb47e7d0c3da.png)

## Expected behavior

The menu should be on top:

![image](https://user-images.githubusercontent.com/154725/95314353-7ddf5300-0891-11eb-8c26-12779ce51776.png)

## Environment

- **lime-elements** version: 28.5.6 (verified ok in 28.5.5)
- Framework used: bug exists in docs [example](http://lime-documentation-lime-elements.s3-website-eu-west-1.amazonaws.com/versions/28.5.6/#/component/limel-select)
- Logs:

**Comment by anderssonjohan** [comment]
Did not see this issue when writing #1020, probably a related z-index war! :)

**Comment by adrianschmidt** [comment]
I just added #1107, which will make z-indexes overridable by the consumer. We may still want to tweak our default values after that, but it's a good starting point for very little effort.
